import os
import streamlit as st
import requests
import json
from dotenv import load_dotenv
from fastapi.responses import RedirectResponse
from pydantic import BaseModel
from fastapi import Body, FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse
from fastapi import FastAPI
from dotenv import load_dotenv
# import pymongo import Mongoclient
import uvicorn
# import openai

load_dotenv()

api_key = os.getenv("OPENAI_API_KEY")

app = FastAPI(title="Daily sales classification API", description="API for mapping labels")


all_pms_data = [
  {
    "anandsystems": {
      "Taxable Rent": "transient retail",
      "Exempted Rent": "transient retail",
      "Exempted Tax": "rooms tax exemptions",
      "cash": "cash",
      "Visa": "visamc rooms",
      "Master Card": "visamc rooms",
      "Room Rental": "transient retail",
      "Tax": "rooms sales tax",
      "No-Show/Cancel Rent": "guaranteed no show rooms",
      "Hotel Cabana Pillow": "miscellaneous income",
      "Early Check-in Fee": "miscellaneous income",
      "Late Checkout Fee": "late checkout fees",
      "Smoking Fee": "smoking fees",
      "Bottled Water": "bottled water",
      "Other Charges": "miscellaneous income",
      "Taxable Charge": "miscellaneous income",
      "Exempted Charge": "miscellaneous income",
      "Discover": "discover rooms",
      "American Express": "amex rooms",
      "Bad Debts": "write off",
      "Discount": "discount",
      "V/Maint Rooms": "Out of Order",
      "R/Ready Rooms": "Vacant rooms",
      "V/Clean Rooms": "Vacant Rooms",
      "V/Ready Rooms": "Vacant Rooms",
      "O/Clean Rooms": "Out of Order",
      "V/Dirty Rooms": "Out of Order",
      "Room Sold" : "Room Sold",
    "Guest Ledger": "Guest Ledger",
    "Account Receivable Ledger": "Transfer to Direct Billing from Guest Ledger",
    "Advance Deposit": "Advances transferred out",
    "Inhouse Deposit": "Guest Ledger"

      
    }
  },
  {
    "autoclerk": {
    "Room Rent": "transient retail",
    "Rollaways": "rollawayscribs",
    "PETS": "pet fees",
    "Cancellation Charge": "cancellation fees",
    "No Show Charge": "guaranteed no show rooms",
    "Room Correction": "miscellaneous income",
    "FX2 Only": "miscellaneous income",
    "Late Check Out": "late checkout fees",
    "Early Check In": "miscellaneous income",
    "Cash": "cash",
    "Check": "checks",
    "Innkeepers Tax": "rooms sales tax",
    "State Sales Tax": "state tax",
    "Sale Tax": "rooms sales tax",
    "County Tax": "rooms city tax",
    "American Express": "amex rooms",
    "Discover(VB)": "discover rooms",
    "Discover / Novus /": "discover rooms",
    "Mastercard": "visamc rooms",
    "Discover": "discover rooms",
    "Visa (S4)": "visamc rooms",
    "Visa": "visamc rooms",
    "Misc Non-Taxable": "miscellaneous income",
    "Gift Shop": "gift shop sales",
    "Smoking": "smoking fees",
    "Pet Fees": "pet fees",
    "BW Free Night": "complimentary rooms",
    "Travelcards BW": "misc. credit card payment",
    "Complimentary Per": "complimentary rooms",
    "EFT PAYMENT": "eftwire payments",
    "Property Damage": "miscellaneous income",
    "CONNECTING ROOM": "transient retail",
    "Miscellaneous Tax": "rooms city tax",
    "Miscellaneous No Tax": "miscellaneous income",
    "Occupied": "Rooms sold",
    "Out of Order": "Out of Order",
    "Vacant Clean": "Vacant Rooms",
    "Soda-bottle": "miscellaneous income",
    "Candy": "miscellaneous income",
    "Chips": "miscellaneous income",
    "Energy Drink": "miscellaneous income",
    "Soda-can": "miscellaneous income",
    "Softener": "miscellaneous income",
    "Shipping & Handling": "miscellaneous income"
    }
  },
  {
    "checkinn": {
    "room rental": "transient retail",
    "telephone": "telephone income local long distance",
    "State Tax": "rooms sales tax",
    "City Tax": "rooms city tax",
    "cash": "cash",
    "Visa/MC": "visamc rooms",
    "package exchange": "package exchange",
    "Discover": "discover rooms",
    "Diners": "misc. credit card payment",
    "Room Dep": "miscellaneous income",
    "Pet": "pet fees",
    "Rollway": "rollawayscribs",
    "Misc": "miscellaneous income",
    "Damages": "miscellaneous income",
    "Vending": "miscellaneous income",
    "Rate Adj": "room allowances",
    "Vacant Clean": "Vacant Rooms",
    "Vacant Dirty": "Out Of Order",
    "Out of Order/Storage": "Out Of Order",
    "Complimentary Rooms": "Complimentary Rooms"
    }
  },
  {
  "choiceadvantage": {
    "Rollaway Charge (RL)": "rollawayscribs",
    "Room Charge (RM)": "transient retail",
    "Destination Fee (TL)": "miscellaneous income",
    "Pet Charge (PET)": "pet fees",
    "Occupancy Tax (T3)": "rooms county occupancy tax",
    "Discover (DS)": "discover rooms",
    "American Express (AX)": "amex rooms",
    "Cash (CA)": "cash",
    "Master Card (MC)": "visamc rooms",
    "Visa Payment (VI)": "visamc rooms",
    "Other Revenue": "miscellaneous income",
    "Day Use Rooms": "Day Use rooms",
    "Miscellaneous (MS)": "miscellaneous income",
    "American Express (AX)": "amex rooms",
    "Writeoff (WO)": "Writeoff/Bad debts",
    "Room Charge (RM)": "transient retail",
    "Room Upgrade (RMU)": "miscellaneous income",
    "Meeting Room (MR)": "banquet room rental",
    "City/County Tax (CF2)": "room city tax",
    "Vending Commission (VC)": "miscellaneous income",
    "Electronic Funds Transfer (EFT)": "eftwire payments",
    "Franchise Credit (FC)": "Franchise credits",
    "Visa Payment (Vl)": "visamc rooms",
    "Rollaway Charge (RL)": "Rollaway charge",
    "Discover (DS)": "Discover rooms",
    "No Show Charge (NS)": "guaranteed no show rooms",
    "Guest Refund (GR)": "Guest refunds",
    "Comp Rooms": "Complimentary Rooms",
    "Out Of Order": "Out of Order",
"Advance Deposit Transferred Out": "Advances transferred out",
"Credits": "Payments Received Towards City Ledger",
"Adjustments": "Payments Received Towards City Ledger",
"Debits": "Transfer to Direct Billing from Guest Ledger",
"Transfer To Accounts Receivable": "Transfers to Direct Billing from Guest Ledger"
    }
  },
  {
    "cloudbeds": {
 "comps": "Complimentary Rooms",
    "Blocks": "Out of Order",
    "Room Rate": "transient retail",
    "Rooms Tax 10%": "rooms sales tax",
    "Visa": "visamc rooms",
    "Mastercard": "visamc rooms",
    "American Express": "amex rooms",
    "Discover": "discover rooms",
    "Pet Fee (25 pounds or less)": "Pet fee",
    "Late Checkout (AFTER 1pm)": "late fee",
    "Check": "Check",
    "Excessive Damage Fee": "damages",
    "City of Sacramento Tourism": "City of Sacramento Tourism Fee",
    "Smoking Fee": "Smoking fee",
    "State Tourism": "State Tourism",
    "Room Revenue - Cancelation": "Cancellation fee",
    "Late Checkout (12pm-1pm)": "late fee",
    "Room Revenue - Manual": "transient retail",
    "Pet Fee (Over 25 pounds)": "Pet fee",
    "Mastercard": "visamc rooms",
    "Early Check-in Fee (before 3:00pm PST)": "early check in fee",
    "Revenue By Adjustment": "transient retail",
    "TOT": "TOT"
      

    }
  },
  {
    "fosse": {
  "Early Departure Rebat": "early departure fees",
  "Convention and Touris": "Other taxes",
  "Convention and Touris exemption": "Other taxes",
  "Rest - Room Charge": "misc. credit card payment",
  "Restaurant Room Charg": "misc. credit card payment",
  "Room Rebate-Groups": "room allowances",
  "Room Charge-Lease/Con": "transient retail",
  "Room Charge-Groups": "transient retail",
  "Room Rebate-Bus Trans": "room allowances",
  "Room Rebate-Plea Tran": "room allowances",
  "Room Rebate-Lease/Con": "room allowances",
  "Room Rebate-Special": "room allowances",
  "Room Rebate-G.N.S.": "room allowances",
  "Room Rebate-Day Rate": "room allowances",
  "Adj. Market Beer": "restaurant one beverage allowances",
  "Facility Charge": "room service service charge",
  "Banquet Gratuity": "f and b tips",
  "Adj. Market Packaged": "restaurant one food allowances",
  "Adj. Market Beverage": "restaurant one food allowances",
  "Adj. Market Sundries": "restaurant one food allowances",
  "Micros Out Of Balance": "restaurant one food allowances",
  "Adj. Market Liquor": "restaurant one beverage allowances",
  "Adj. Market Wine": "restaurant one beverage allowances",
  "Comp Breakfast": "breakfast coupons allowances",
  "Dinner Delivery": "room service food sales dinner",
  "Outside Catering": "banquet other miscellaneous revenue",
  "Bottled Water": "restaurant one beverage sales other",
  "Bistro Fresh Food": "restaurant one food sales lunch",
  "Market Fresh Food": "restaurant one food sales lunch",
  "Market Frozen Food": "restaurant one food sales lunch",
  "Adj. Market Frozen Fo": "restaurant one food sales lunch",
  "Adj. Market Fresh Foo": "restaurant one food sales lunch",
  "Rebate - Restaurant F": "restaurant one food sales lunch",
  "Elite Welcome Gift": "gift certificate 23140",
  "Gift Shop Sls": "gift shop sales",
  "Gift Shop Rebate": "gift shop sales",
  "Gift Shop Cigarettes": "gift shop sales",
  "Gift Card Sale": "gift certificate 23140",
  "Gift Card Redemption": "gift certificate 23140",
  "Data Service Rebate": "miscellaneous income",
  "Room Safe Rebate": "miscellaneous income",
  "Rebate-Rest 3rd Party": "miscellaneous income",
  "Vending Machine Rebate": "miscellaneous income",
  "Energy Fee Rebate": "miscellaneous income",
  "Alcoholic Beverages": "banquet beverage revenue beer",
  "Resort Fee": "miscellaneous income",
  "Resort Fee - Rebate": "miscellaneous income",
  "CYC Free Dessert Rebate": "miscellaneous income",
  "CYC Free Fax Rebate": "miscellaneous income",
  "CYC No-Walk Rebate": "miscellaneous income",
  "VIDEO GAME REBATE": "miscellaneous income",
  "Hospitality Rebate": "room allowances",
  "Gratuity": "Tips",
  "Room Damage Reimburse": "miscellaneous income",
  "Loss & Damage Guest E": "miscellaneous income",
  "Room Type Penalty": "miscellaneous income",
  "No Walk Elite Penalty": "miscellaneous income",
  "Rebate Local Phone": "miscellaneous income",
  "Rebate-Long Distance": "miscellaneous income",
  "CYC Free Phone Rebate": "miscellaneous income",
  "Admin Phone Rebates": "miscellaneous income",
  "Rebate - Parking": "parking income",
  "Music Rebate": "miscellaneous income",
  "Movie Rebate": "movie rental",
  "Early Departure Fee": "early departure fees",
  "ROOMS OCCUPIED": "Rooms sold",
  "Late Payment Fee": "late checkout fees",
  "Rollaway Bed Rental": "rollawayscribs",
  "Van Charge": "miscellaneous income",
  "MBV Occ Premium": "MBV Redemption",
  "MBV Redemption": "MBV Redemption",
  "Room Charge-Bus Trans": "transient retail",
  "Room Charge-Pleas Tra": "transient retail",
  "Room Charge-Special": "transient retail",
  "Room Charge-G.N.S": "guaranteed no show rooms",
  "Room Charge-Day Rate": "transient retail",
  "Rate Adjustment": "room allowances",
  "Rooms Coupon Promo Re": "room allowances",
  "Beer": "restaurant one beverage sales beer",
  "Market Beer": "restaurant one beverage sales beer",
  "Honor Bar Beverage": "restaurant one beverage sales other",
  "Honor Beverage": "restaurant one beverage sales other",
  "Banquet Beverage": "banquet beverage revenue beverage",
  "Business Center": "miscellaneous income",
  "Market Packaged Food": "restaurant one beverage sales other",
  "Market Beverage": "restaurant one beverage sales other",
  "Market Sundries": "restaurant one beverage sales other",
  "Liquor": "restaurant one beverage sales liquor",
  "Market Liquor": "restaurant one beverage sales liquor",
  "Wine": "restaurant one beverage sales wine",
  "Market Wine": "restaurant one beverage sales wine",
  "Breakfast Express": "restaurant one food sales breakfast",
  "Breakfast Food": "restaurant one food sales breakfast",
  "Banquet Breakfast": "banquet food revenue breakfast",
  "CMN Breakfast Campaig": "restaurant one food sales breakfast",
  "Banquet Coffee Break": "banquet food revenue coffee break",
  "Dinner Food": "restaurant one food sales dinner",
  "Banquet Dinner": "banquet food revenue dinner",
  "Lunch Food": "restaurant one food sales lunch",
  "Banquet Lunch": "banquet food revenue lunch",
  "Liquor & Beverage Cos": "restaurant one beverage sales other",
  "Banquet Service Charg": "banquet surcharges and service charges",
  "Catering Service": "banquet surcharges and service charges",
  "F & B Promotions": "restaurant one beverage sales other",
  "Elite Gift Guarantee": "gift certificate 23140",
  "Pool 3rd Party": "miscellaneous income",
  "Cancellation Fee": "cancellation fees",
  "Washer/Dryer Income": "guest laundrydry cleaning",
  "Data Service": "internet income",
  "Meeting Room A": "banquet room rental",
  "Meeting Room B": "banquet room rental",
  "Meeting Room C": "banquet room rental",
  "Meeting Room D": "banquet room rental",
  "Audio Visual": "banquet av rental revenue",
  "Meeting Room Linen": "banquet room rental",
  "Overhead Income": "miscellaneous income",
  "Flipchart Income": "miscellaneous income",
  "Membership Income": "miscellaneous income",
  "AARP Discount": "miscellaneous income",
  "Fax Charge": "miscellaneous income",
  "Game Room": "miscellaneous income",
  "Fire Logs": "miscellaneous income",
  "Guest Amenities": "miscellaneous income",
  "Groceries": "miscellaneous income",
  "Adj - Fire Logs": "miscellaneous income",
  "Over The Counter Sale": "miscellaneous income",
  "Ticket Sales": "miscellaneous income",
  "Vending Income": "miscellaneous income",
  "Room Safe Income": "miscellaneous income",
  "Baggage Handling": "miscellaneous income",
  "Restaurant 3rd Party": "miscellaneous income",
  "Starbucks Revenue": "miscellaneous income",
  "Misc. Revenue - Ticke": "miscellaneous income",
  "Vending Commissions": "commission income",
  "Loyalty Bonus Points": "miscellaneous income",
  "MBV Promotion": "miscellaneous income",
  "Outside Restaurant": "miscellaneous income",
  "Sundries": "miscellaneous income",
  "Newspapers": "miscellaneous income",
  "Packaged Food Sales": "miscellaneous income",
  "State Cost - Recovery": "miscellaneous income",
  "Misc. Revenue - Trans": "miscellaneous income",
  "Audio Visual Commissi": "commission income",
  "Resi Deli (nontaxable": "miscellaneous income",
  "Misc. Revenue - Golf": "miscellaneous income",
  "Misc.-Charge Non-tax": "miscellaneous income",
  "Rentals-Misc.": "miscellaneous income",
  "Deli Store": "miscellaneous income",
  "Pizza Sales": "miscellaneous income",
  "Misc. Revenue - Ski P": "miscellaneous income",
  "Nick Your Stay Promo": "miscellaneous income",
  "Slippage": "miscellaneous income",
  "Guestroom Cancellatio": "cancellation fees",
  "ADJ - Guestroom Cance": "cancellation fees",
  "Destination Fee": "miscellaneous income",
  "Destination Fee - Reb": "miscellaneous income",
  "CY Club Application F": "miscellaneous income",
  "CYC Free Fax": "miscellaneous income",
  "Office Supplies": "Miscellaneous expense",
  "AR Payments": "eftwire payments",
  "Music": "miscellaneous income",
  "Valet": "miscellaneous income",
  "VIDEO GAME": "miscellaneous income",
  "Copy Income": "miscellaneous income",
  "Employee Meals": "comp meal allowance a and g",
  "Ladies Room Supplies": "Miscellaneous expense",
  "Manager Close": "Miscellaneous expense",
  "Magazines/Newspapers": "Miscellaneous expense",
  "Safety Program": "Miscellaneous expense",
  "Promo/Coupon Discount": "breakfast coupons allowances",
  "Soap Vending Income": "miscellaneous income",
  "Stamp/Postage Income": "miscellaneous income",
  "Travel Agent Commissi": "Miscellaneous expense",
  "Sls Mgr Entertainment": "Miscellaneous expense",
  "Miscellaneous Charge": "miscellaneous income",
  "Hospitality": "miscellaneous income",
  "Business Incentive Di": "Miscellaneous expense",
  "Disney/AAA Promotion": "Miscellaneous expense",
  "Cleaning Supplies Fd/": "Miscellaneous expense",
  "Cleaning Supplies Res": "Miscellaneous expense",
  "Food Purchase": "Miscellaneous expense",
  "Comp Evening Food": "comp meal allowance room service",
  "General Building": "Miscellaneous expense",
  "Grocery Purchase": "Miscellaneous expense",
  "Incentive Expense": "Miscellaneous expense",
  "Local Mileage": "Miscellaneous expense",
  "General Expense Fd/Hs": "Miscellaneous expense",
  "General Expense Rest": "Miscellaneous expense",
  "Misc Serving Equipmen": "Miscellaneous expense",
  "General Expense Mgt": "Miscellaneous expense",
  "Permits & Licenses": "Miscellaneous expense",
  "Paper Supplies": "Miscellaneous expense",
  "Outside Services Expe": "Miscellaneous expense",
  "Market Food Cost": "Miscellaneous expense",
  "Market Beverage Cost": "Miscellaneous expense",
  "Empl Uniform Purchase": "Miscellaneous expense",
  "Health Club": "miscellaneous expense",
  "Health Spa Voucher": "miscellaneous expense",
  "Comp Night Voucher": "comp meal allowance room service",
  "Marriott Direct Charg": "miscellaneous expense",
  "Adj - T C R Fund": "miscellaneous expense",
  "Security Deposit": "eftwire payments",
  "T C R Fund - Optional": "miscellaneous expense",
  "Charitable Contributi": "miscellaneous expense",
  "Non TEFRA Offset": "miscellaneous expense",
  "Non TEFRA Sales": "miscellaneous expense",
  "Trade Out": "miscellaneous expense",
  "Cxl Resv Keep": "miscellaneous expense",
  "Japanese Credit Burea": "misc. credit card payment",
  "MBS AR Pmt Settlement": "miscellaneous expense",
  "British Air Total Act": "miscellaneous expense",
  "Balance Forward - R/T": "miscellaneous expense",
  "Balance Forward - Inc": "miscellaneous expense",
  "Rest- Mobile Dine CC": "misc. credit card payment",
    "Local Phone": "telephone income local long distance",
  "State Farm Local Call": "telephone income local long distance",
  "Telecom Bundle": "telephone income local long distance",
  "Bundle Offset": "telephone income local long distance",
  "Long Distance Phone": "telephone income local long distance",
  "Admin Long Distance P": "telephone income local long distance",
  "Phone": "telephone income local long distance",
  "Admin Local Phone": "telephone income local long distance",
  "Admin Phone Svc Charg": "telephone income local long distance",
  "Accounting Adjustment": "miscellaneous income",
  "Pre-Settle-CYIS Only": "miscellaneous income",
  "Instant Redemption Aw": "miscellaneous income",
  "Certificate Redemptio": "gift certificate 23140",
  "Redemption Offset": "MBV Redemption",
  "Refunds": "miscellaneous expense",
  "Billed Gift Certifica": "gift certificate 23140",
  "Write Off Reserve All": "Write offs/Bad debts",
  "Chargeback - AMEX": "Chargebacks",
  "Chargeback-Bank Cards": "Chargebacks",
  "Chargeback-Diners Clu": "Chargebacks",
  "Unpaid Balance": "Write offs/Bad debts",
  "City Tax": "rooms city tax",
  "County Tax": "rooms county occupancy tax",
  "City Tax exemption": "rooms city tax exemptions",
  "County Tax exemption": "rooms county occupancy tax exemptions",
  "Occupancy Sales Tax": "rooms sales tax",
  "State Occupancy Tax": "rooms city tax",
  "Occupancy Sales Tax exemption": "rooms county occupancy tax exemptions",
  "State Occupancy Tax exemption": "rooms city tax exemptions",
  "Energy Fee Tax": "Other taxes",
  "OTC Tax Liability": "Other taxes",
  "Parking Tax": "Other taxes",
  "Room Tax": "rooms city tax",
  "Stadium Tax": "Other taxes",
  "Bed Tax": "Other taxes",
  "Sales Tax Other Room": "rooms sales tax",
  "Sales Tax": "f and b sales tax",
  "Calif/Local Tourism F": "Tourism Fee",
  "Calif/Local Tourism A": "Tourism Fee",
  "Tax": "Other taxes",
  "GST-Goods and Service": "f and b sales tax",
  "PST-Provincial Sales": "f and b sales tax",
  "Tax Exempt - F&B": "f and b tax exemptions",
  "Tax Exempt - Organiza": "rooms city tax exemptions",
  "Tax Exempt - Airlines": "rooms city tax exemptions",
  "Tax Exempt - Perm Res": "rooms city tax exemptions",
  "Fax Tax": "telephone tax",
  "Honor Tax": "georgia hotel motel fee",
  "Restaurant Tax": "rooms county occupancy tax",
  "Tax - Liquor": "f and b sales tax",
  "Meeting Room Tax": "rooms sales tax",
  "Sales Tax - Vending": "f and b sales tax",
  "Valet Tax": "rooms city tax",
  "Energy Fee Tax exemption": "rooms city tax exemptions",
  "OTC Tax Liability exemption": "rooms city tax exemptions",
  "Parking Tax exemption": "rooms city tax exemptions",
  "Room Tax exemption": "rooms tax exemptions",
  "Stadium Tax exemption": "rooms city tax exemptions",
  "Bed Tax exemption": "rooms county occupancy tax exemptions",
  "Sales Tax Other Room exemption": "rooms sales tax",
  "Sales Tax exemption": "rooms sales tax",
  "Calif/Local Tourism F exemption": "rooms tax exemptions",
  "Calif/Local Tourism A exemption": "rooms tax exemptions",
  "Tax exemption": "rooms tax exemptions",
  "GST-Goods and Service exemption": "f and b sales tax",
  "PST-Provincial Sales exemption": "f and b sales tax",
  "Tax Exempt - F&B exemption": "f and b tax exemptions",
  "Tax Exempt - Organiza exemption": "Other taxes",
  "Tax Exempt - Airlines exemption": "Other taxes",
  "Tax Exempt - Perm Res exemption": "Other taxes",
  "Fax Tax exemption": "telephone tax",
  "Honor Tax exemption": "Other taxes",
  "Restaurant Tax exemption": "f and b sales tax",
  "Tax - Liquor exemption": "f and b sales tax",
  "Meeting Room Tax exemption": "Other taxes",
  "Sales Tax - Vending exemption": "f and b sales tax",
  "Valet Tax exemption": "Other taxes",
  "American Express": "amex rooms",
  "Rest-AMEX": "amex f and b",
  "Rest -AMEX Offset": "amex f and b",
  "Rest - AMEX Transfer": "amex f and b",
  "AMEX Transfer": "amex f and b",
  "Cash": "cash",
  "Cash - Restaurant": "cash",
  "Petty Cash Expense": "paid outs",
  "Front Office Cash": "cash",
  "British Air Cash Paid": "cash",
  "British Air Cash In": "cash",
  "Check": "checks",
  "Electronic Check": "checks",
  "Returned Check": "checks",
  "Discover": "discover rooms",
  "Wire Transfer": "eftwire payments",
  "Transfer": "eftwire payments",
  "Diners Club": "misc. credit card payment",
  "Transfer C/D": "eftwire payments",
  "Rest-Bank Cards": "misc. credit card payment",
  "Rest -Bank Cards Offs": "misc. credit card payment",
  "Rest-Diners Club": "misc. credit card payment",
  "Rest -Diners Club Off": "misc. credit card payment",
  "Bank Card Transfer": "misc. credit card payment",
  "Rest - Bank Card Tran": "misc. credit card payment",
  "Diners Transfer": "misc. credit card payment",
  "Enroute": "misc. credit card payment",
  "JCB": "misc. credit card payment",
  "Rest - Diners Club Tr": "misc. credit card payment",
  "Paid Out": "paid outs",
  "Master Card": "visamc rooms",
  "VISA": "visamc rooms",
'City Fee': 'City Fee',
'City Fee exemption': 'City Fee',
'Complimentary Rooms': 'Complimentary',
'OUT OF ORDER': 'Out of Order',
'Rate Adjustment ': 'room allowances',
'Rooms Coupon Promo Re ': 'room allowances',
'Test Meals': 'comp meal allowance a and g',
'Telephone Commission': 'telephone income local long distance',
'Cigarettes': 'smoking fees',
'Garage Parking': 'parking income',
'Daily Parking': 'parking income',
'Valet Parking': 'parking income',
'Breakfast Coupon': 'breakfast coupons allowances',
'F&B Package Rev': 'package exchange',
'F&B Package Expense': 'package exchange',
'CYC Dessert Coupon': 'breakfast coupons allowances',
'Bad Debt': 'Write offs/Bad debts',
'Atlanta Package': 'miscellaneous income',
'FRANCHISE FEES': 'franchise reimbursement payment',
'Movie': 'movie rental',
'Breakfast Coupon Cost': 'Miscellaneous expense',
'BREAKFAST COVERS': 'Miscellaneous expense',
'LUNCH COVERS': 'Miscellaneous expense',
'DINNER COVERS': 'Miscellaneous expense',
'COVERS OFFSET': 'Miscellaneous expense',
'CHARGED TIPS': 'f and b tips',
'CHARGED RECEIPTS': 'Tips',
'CHARGED REC.+TIP OFFS': 'Tips',
'RT  ROOM TAX STAT': 'rooms city tax',
'T2  STATE OCCUPANCY T': 'rooms city tax',
'T9  GIFT SHOP SALES T': 'f and b sales tax',
'ROOMS SOLD': 'Rooms sold',
'VACANT ROOMS': 'Vacant Rooms',
'COMP ROOMS': 'Complimentary rooms',
'Office Rental': 'miscellaneous income',
'Telecom Tax exemption': 'miscellaneous income',
'Telephone Tax exemption': 'miscellaneous income',
'Pet Charge': 'Pet fee',
'Employee Relations': 'miscellaneous income',
'Telephone Tax': 'miscellaneous income',
'Telecom Tax': 'miscellaneous income',
'Pet Cleaning Fee': 'Pet fee',
'Smoke Free Environmen': 'smoking fees',
'Rm Chg PENT T2 Transi': 'transient retail',
'Rm Chg PENT T3 Group': 'transient retail',
'Adj PENT T3 Contract': 'transient retail',
'Rm Chg STDO T4 Contra': 'transient retail',
'Adj PENT T2 Group': 'transient retail',
'Rm Chg PENT T2 Group': 'transient retail',
'Rm Chg PENT T3 Contra': 'transient retail',
'Rm Chg STDO T3 Transi': 'transient retail',
'Adj STDO T1 Group': 'transient retail',
'Adj PENT T2 Contract': 'transient retail',
'Adj STDO T1 Transient': 'transient retail',
'Adj STDO T3 Transient': 'transient retail',
'Adj STDO T4 Transient': 'transient retail',
'Rm Chg PENT T4 Transi': 'transient retail',
'Adj STDO T1 Contract': 'transient retail',
'Adj STDO T3 Contract': 'transient retail',
'Adj PENT T4 Contract': 'transient retail',
'Adj PENT T1 Contract': 'transient retail',
'Rm Chg STDO T1 Contra': 'transient retail',
'Adj STDO T4 Group': 'transient retail',
'Adj STDO T3 Group': 'transient retail',
'Rm Chg STDO T4 Transi': 'transient retail',
'Adj STDO T2 Transient': 'transient retail',
'Rm Chg STDO T3 Group': 'transient retail',
'Rm Chg PENT T1 Transi': 'transient retail',
'Rm Chg PENT T2 Contra': 'transient retail',
'Rm Chg PENT T4 Group': 'transient retail',
'Adj PENT T3 Group': 'transient retail',
'Adj PENT T1 Group': 'transient retail',
'Rm Chg STDO T2 Contra': 'transient retail',
'Rm Chg STDO T1 Transi': 'transient retail',
'Rm Chg STDO T1 Group': 'transient retail',
'Rm Chg PENT T3 Transi': 'transient retail',
'Rm Chg STDO T4 Group': 'transient retail',
'ROOMS VACANT': 'Vacant Rooms',
'TOTAL ROOMS-OUT OF ORDER': 'Out of Order',
'Wage Repayment': 'miscellaneous income',
'Rebate-Pool 3rd Party': 'miscellaneous income',
'Rm Chg PENT T1 Group': 'transient retail',
'Adj PENT T4 Group': 'transient retail',
'Rm Chg STDO T3 Contra': 'transient retail',
'Rm Chg PENT T4 Contra': 'transient retail',
'Adj STDO T2 Contract': 'transient retail',
'Rm Chg PENT T1 Contra': 'transient retail',
'Rm Chg STDO T2 Transi': 'transient retail',
'Adj STDO T2 Group': 'transient retail',
'Rm Chg STDO T2 Group': 'transient retail',
'Adj STDO T4 Contract': 'transient retail'
    }
  },
  {
    "hotelkey": {
    "GUEST ROOM": "transient retail",
    "EXTRA ADULT": "transient retail",
    "EXTRA NO SHOW ROOM REVENUE": "transient retail",
    "GUEST ROOM HONORS": "transient retail",
    "PREPAID EARLY CHECKOUT": "early departure fees",
    "ROOM UPGRADE": "transient-retail",
    "ADVANCE PURCHASE 3.5% DISCOUNT": "advance purchase 3.5% discount",
    "ADVANCE PURCHASE 3.5%": "advance purchase 3.5%",
    "DISCOUNT": "discount",
    "ADVANCE PURCHASE CHANGE FEE": "purchase change fee",
    "BALANCE TRANSFER": "balance transfer",
    "CANCELLATION CHARGE": "cancellation charges",
    "CHARGE-BACKS": "charge-backs",
    "CLEANING FEE": "cleaning fee",
    "COFFEE BREAK": "coffee break",
    "COMMISSION REVENUE": "commission charge",
    "COPIES": "copies",
    "EARLY ARRIVAL": "early arrival",
    "FAX": "fax",
    "GUEST CERTIFICATE": "guest certificate",
    "GUEST EQUIPMENT RENTAL": "guest equipment",
    "HOME2MKT": "home2mkt",
    "INTERNET ACCESS": "internet income",
    "LATE CANCEL ROOM REVENUE": "late cancel room revenue",
    "LATE DEPARTURE": "late departure",
    "MEETING ROOM": "meeting room",
    "MISC REVENUE": "miscellaneous income",
    "MISC REVENUE NON-TAXABLE": "misc revenue non-taxable",
    "NO SHOW ROOM REVENUE": "guaranteed no show rooms",
    "PET FEE": "pet fees",
    "PET FEE 1 TO 4 NIGHTS": "pet fees",
    "PET FEE 5 OR MORE NIGHTS": "pet fees",
    "PET FEE ALLOW": "pet fees",
    "PET FEE MANUAL": "pet fees",
    "PREMIUM INTERNET ACCESS": "internet income",
    "PREPAID LATE CANCEL ROOM": "cancellation fees",
    "RETURNED CHECKS": "miscellaneous income",
    "SERVICE ANIMAL": "miscellaneous income",
    "SMOKING FEE": "smoking fees",
    "TELEPHONE COMMISSIONS": "commission income",
    "TELEPHONE-LD (FOREIGN)": "telephone income local long distance",
    "TELEPHONE-LD (INTERSTATE)": "telephone income local long distance",
    "TELEPHONE-LOCAL": "telephone income local long distance",
    "VALET LAUNDRY": "guest laundrydry cleaning",
    "VENDING MACHINE REVENUE": "miscellaneous income",
    "MISC COUNTY TAX": "rooms sales tax",
    "MISC STATE TAX": "rooms sales tax",
    "RM COUNTY TAX": "rooms county occupancy tax",
    "RM HOTEL MOTEL FEE": "miscellaneous income",
    "RM OCCUPANCY TAX": "rooms county occupancy tax",
    "RM STATE TAX": "rooms sales tax",
    "CASH": "cash",
    "CHECK": "checks",
    "AMEX": "amex rooms",
    "MASTER": "visamc rooms",
    "VISA": "visamc rooms",
    "Rooms Down": "Out of Order rooms",
    "Rooms Sold": "Rooms sold",
    "Rooms Vacant": "Vacant Rooms",
    "Rooms Dirty": "Out of Order rooms",
    "Comp Rooms": "Complimentary rooms",
    "DISCOVER": "discover rooms",
    "TELEPHONE-LD (INTRASTATE)": "telephone income local long distance",
    "BANQUETS - SERVICE CHARGE": "banquet other miscellaneous revenue",
    "PVR ONREQUEST HOUSEKEEPING": "miscellaneous income",
    "MEETING ROOM": "banquet room rental",
    "NO SHOW ROOM REVENUE": "guaranteed no show rooms",
    "MUSIC": "miscellaneous income",
    "GUEST EQUIPMENT RENTAL": "miscellaneous income",
    "BUSINESS CENTER-OTHERS": "miscellaneous income",
"In House Net Change": "Guest Ledger",
    "House Account Net Change": "House Account transferred",
    "Total Closed Folio Net Change": "Closed Folio",
    "Direct Bill Net Change": "Transfer to Direct Billing from Guest Ledger",
    "Advance Deposit Net Change": "Advances transferred out",
    "Group Master Net Change": "Group Ledger transferred out"
    }
  },
    {
    "peponq": {
    "GUEST ROOM": "transient retail",
    "EXTRA ADULT": "transient retail",
    "EXTRA NO SHOW ROOM REVENUE": "transient retail",
    "GUEST ROOM HONORS": "transient retail",
    "PREPAID EARLY CHECKOUT": "early departure fees",
    "ROOM UPGRADE": "transient-retail",
    "ADVANCE PURCHASE 3.5% DISCOUNT": "advance purchase 3.5% discount",
    "ADVANCE PURCHASE 3.5%": "advance purchase 3.5%",
    "DISCOUNT": "discount",
    "ADVANCE PURCHASE CHANGE FEE": "purchase change fee",
    "BALANCE TRANSFER": "balance transfer",
    "CANCELLATION CHARGE": "cancellation charges",
    "CHARGE-BACKS": "charge-backs",
    "CLEANING FEE": "cleaning fee",
    "COFFEE BREAK": "coffee break",
    "COMMISSION REVENUE": "commission charge",
    "COPIES": "copies",
    "EARLY ARRIVAL": "early arrival",
    "FAX": "fax",
    "GUEST CERTIFICATE": "guest certificate",
    "GUEST EQUIPMENT RENTAL": "guest equipment",
    "HOME2MKT": "home2mkt",
    "INTERNET ACCESS": "internet income",
    "LATE CANCEL ROOM REVENUE": "late cancel room revenue",
    "LATE DEPARTURE": "late departure",
    "MEETING ROOM": "meeting room",
    "MISC REVENUE": "miscellaneous income",
    "MISC REVENUE NON-TAXABLE": "misc revenue non-taxable",
    "NO SHOW ROOM REVENUE": "guaranteed no show rooms",
    "PET FEE": "pet fees",
    "PET FEE 1 TO 4 NIGHTS": "pet fees",
    "PET FEE 5 OR MORE NIGHTS": "pet fees",
    "PET FEE ALLOW": "pet fees",
    "PET FEE MANUAL": "pet fees",
    "PREMIUM INTERNET ACCESS": "internet income",
    "PREPAID LATE CANCEL ROOM": "cancellation fees",
    "RETURNED CHECKS": "miscellaneous income",
    "SERVICE ANIMAL": "miscellaneous income",
    "SMOKING FEE": "smoking fees",
    "TELEPHONE COMMISSIONS": "commission income",
    "TELEPHONE-LD (FOREIGN)": "telephone income local long distance",
    "TELEPHONE-LD (INTERSTATE)": "telephone income local long distance",
    "TELEPHONE-LOCAL": "telephone income local long distance",
    "VALET LAUNDRY": "guest laundrydry cleaning",
    "VENDING MACHINE REVENUE": "miscellaneous income",
    "MISC COUNTY TAX": "rooms sales tax",
    "MISC STATE TAX": "rooms sales tax",
    "RM COUNTY TAX": "rooms county occupancy tax",
    "RM HOTEL MOTEL FEE": "miscellaneous income",
    "RM OCCUPANCY TAX": "rooms county occupancy tax",
    "RM STATE TAX": "rooms sales tax",
    "CASH": "cash",
    "CHECK": "checks",
    "AMEX": "amex rooms",
    "MASTER": "visamc rooms",
    "VISA": "visamc rooms",
    "Rooms Down": "Out of Order rooms",
    "Rooms Sold": "Rooms sold",
    "Rooms Vacant": "Vacant Rooms",
    "Rooms Dirty": "Out of Order rooms",
    "Comp Rooms": "Complimentary rooms",
    "DISCOVER": "discover rooms",
    "TELEPHONE-LD (INTRASTATE)": "telephone income local long distance",
    "BANQUETS - SERVICE CHARGE": "banquet other miscellaneous revenue",
    "PVR ONREQUEST HOUSEKEEPING": "miscellaneous income",
    "MEETING ROOM": "banquet room rental",
    "NO SHOW ROOM REVENUE": "guaranteed no show rooms",
    "MUSIC": "miscellaneous income",
    "GUEST EQUIPMENT RENTAL": "miscellaneous income",
    "BUSINESS CENTER-OTHERS": "miscellaneous income",
"In House Net Change": "Guest Ledger",
    "House Account Net Change": "House Account transferred",
    "Total Closed Folio Net Change": "Closed Folio",
    "Direct Bill Net Change": "Transfer to Direct Billing from Guest Ledger",
    "Advance Deposit Net Change": "Advances transferred out",
    "Group Master Net Change": "Group Ledger transferred out"
    }
  },
  {
    "lightspeed": {
    "Rooms Occupied Paid": "Rooms sold",       
    "Room Charge + Allowa": "transient retail",
    "Room Chrg - Premium": "transient retail", 
    "Room Chrg - Standard": "transient retail",
    "Room Chrg - eChannel": "transient retail",
    "Room Chrg - Special": "transient retail", 
    "Room Chrg - Wholesal": "transient retail",
    "Room Chrg - Govt./Mi": "transient retail",
    "Room Chrg - Weekend": "transient retail", 
    "Room Chrg - AAA": "transient retail",
    "Room Chrg - Packages": "transient retail",
    "Room Chrg - Advance": "transient retail",
    "Room Chrg - Senior D": "transient retail",
    "Room Chrg - Associat": "transient retail",
    "Rm Chrg - Reward Red": "transient retail",
    "Room Chrg - Complime": "transient retail",
    "Room Chrg - GRP OTH": "transient retail",
    "Room Chrg - GRP - Co": "transient retail",
    "Room Chrg - GRP - As": "transient retail",
    "Room Chrg - GRP Tour": "transient retail",
    "Room Chrg - GRP - Go": "transient retail",
    "Room Charge OPEN": "transient retail",
    "Room Chrg - Contract": "transient retail",
    "Room Chrg Opaque": "transient retail",
    "Room Chrg SVO Tours": "transient retail",
    "Day Use Room Charge": "house use rooms",
    "Room Chrg - GRP Asso": "transient retail",
    "Room Charge HOLD FOR": "transient retail",
    "Key Forfieture": "miscellaneous income",
    "Early Departure Fee": "early departure fees",
    "Guaranteed No Show": "guaranteed no show rooms",
    "Guaranteed No Show-C": "guaranteed no show rooms",
    "Late Checkout Fee": "late checkout fees",
    "Discounts": "transient other discounts",
    "Beer": "banquet beverage revenue beer",
    "Bqt-Beer": "banquet beverage revenue beer",
    "Ctr-Beer": "restaurant one beverage sales beer",
    "Restore Beverage": "restaurant two beverage sales other",
    "Bqt-Liquor": "banquet beverage revenue liqour",
    "Ctr-Liquor": "restaurant two beverage sales liqour",
    "Wine": "restaurant one beverage sales wine",
    "Bqt-Wine": "banquet beverage revenue wine",
    "Ctr-Wine": "restaurant one beverage sales wine",
    "Bqt-Breakfast": "banquet food revenue breakfast",
    "Ctr-Breakfast": "restaurant one food sales breakfast",
    "Express Pass Guara": "misc. credit card payment",
    "Bqt-Dinner": "banquet food revenue dinner",
    "Ctr-Dinner": "restaurant one food sales dinner",
    "Bqt-Lunch": "banquet food revenue lunch",
    "Ctr-Lunch": "restaurant one food sales lunch",
    "GiveX Gift Card": "misc. credit card payment",
    "Givex Gift Card": "misc. credit card payment",
    "Gift Certificates": "gift certificate 23140",
    "Cancellation Fee-Tra": "cancellation fees",
    "Laundry/Valet": "guest laundrydry cleaning",
    "Internet Service In": "internet income",
    "Service Resolution -": "Miscellaneous Income",
    "Access": "misc. credit card payment",
    "F&B Access": "misc. credit card payment",
    "Room Chrg - Other Di": "transient retail",
    "Reservation/Cancella": "miscellaneous income",
    "Resort Service Fee": "miscellaneous income",
    "Other Room Charges": "miscellaneous income",
    "Loyalty Redemption O": "miscellaneous income",
    "Food": "restaurant two other f and b revenue",
    "Gratutity": "Tips",
    "Bqt-Other Beverage": "banquet other miscellaneous revenue",
    "Bqt-Meeting Room": "banquet room rental",
    "Bqt-Other": "banquet other miscellaneous revenue",
    "Bqt-Audio Visual": "banquet av rental revenue",
    "Bqt-Phone Set Up": "telephone income local long distance",
    "Ctr-Other Beverage": "restaurant two beverage sales other",
    "Ctr-Meeting Room": "banquet room rental",
    "Ctr-Audio Visual": "banquet av rental revenue",
    "Ctr-Phone Set Up": "telephone income local long distance",
    "Restore Food": "restaurant two other f and b revenue",
    "Restore Sundries": "miscellaneous income",
    "Fax": "miscellaneous income",
    "Small Balance": "miscellaneous income",
    "In Room Movie": "movie rental",
    "Misc Income": "miscellaneous income",
    "Postage/Shipping": "miscellaneous income",
    "Interest": "miscellaneous income",
    "Misc Non Revenue": "miscellaneous income",
    "Tickets A/P": "miscellaneous income",
    "Florist A/P": "miscellaneous income",
    "Transportation A/P": "miscellaneous income",
    "Certificate Purchase": "miscellaneous income",
    "A/L General": "miscellaneous income",
    "Guest Room Damage": "miscellaneous income",
    "Losses & Damages": "miscellaneous income",
    "Package Items": "miscellaneous income",
    "Other A/P": "miscellaneous income",
    "Gratuity Amentity De": "Tips",
    "Porterage": "miscellaneous income",
    "Gratuity Other": "Tips",
    "Guest Incentive Prog": "miscellaneous income",
    "A/R Non Operating": "miscellaneous income",
    "A/R Misc Expense": "miscellaneous income",
    "A/R Interest Income": "miscellaneous income",
    "A/R TA commission": "miscellaneous income",
    "A/R F&B Settlement": "miscellaneous income",
    "A/R TA Commission": "miscellaneous income",
    "Package Rooms": "package exchange",
    "Package Element Rest": "package exchange",
    "Bqt-Service Charge": "banquet surcharges and service charges",
    "Ctr-Service Charge": "room service service charge",
    "Ctr-Gratuity": "f and b tips",
    "Gratuity Housekeepin": "Tips",
    "Gratuity Promo/Staff": "Tips",
    "A/P General Liab #1": "Miscellaneous Non revenue",
    "A/L General Liab #2": "Miscellaneous Non revenue",
    "A/L General Liab #3": "Miscellaneous Non revenue",
    "A/L General Liab #4": "Miscellaneous Non revenue",
    "A/L Relief Fund": "Miscellaneous Non revenue",
    "EFT (wire Trans) P": "eftwire payments",
    "Marriott Bonvoy In": "Miscellaneous receipts",
    "Vouchers": "miscellaneous income",
    "Certificates - Oth": "gift certificate 23140",
    "Group Commission": "Miscellaneous receipts",
    "Group Settlement": "Miscellaneous receipts",
    "TA Guarantee": "Miscellaneous receipts",
    "Deposit Rcvd - AX": "amex rooms",
    "Deposit Rcvd - DI": "discover rooms",
    "Package": "package exchange",
    "Package Restore": "package exchange",
    "F&B Discover Netwo": "discover f and b",
    "Parking": "parking income",
    "Package Parking": "package exchange",
    "Pet Fee": "pet fees",
    "Manual American Ex": "misc. credit card payment",
    "Manual MasterCard/": "misc. credit card payment",
    "Telephone Local": "telephone income local long distance",
    "Telephone Long Dista": "telephone income local long distance",
    "Long Distance - Inte": "internet income",
    "Attrition": "attrition fees",
    "Currency Exchange": "miscellaneous income",
    "Attrition F&B": "attrition fees",
    "Cxl/Attrition": "miscellaneous income",
    "Gift Certificate Pur": "Miscellaneous receipts",
    "A/R Returned Credit": "miscellaneous income",
    "A/R Credit Card Disc": "miscellaneous income",
    "A/R Writeoff/Bad Deb": "Bad Debts written off",
    "Customer Refund": "miscellaneous income",
    "A/R Bank Charges": "miscellaneous income",
    "A/R Receivable Gener": "miscellaneous income",
    "Diners/Carte Blanc": "misc. credit card payment",
    "Manual Diners/Cart": "misc. credit card payment",
    "F&B Diners/Carte B": "misc. credit card payment",
    "A/R Lockbox": "miscellaneous income",
    "A/R Cancellation": "miscellaneous income",
    "China Union Pay": "misc. credit card payment",
    "Repost Of A/R": "miscellaneous income",
    "County Tax": "rooms county occupancy tax",
    "Room Tax": "rooms sales tax",
    "Ctr-Other": "miscellaneous income",
    "Re-Bill No GST": "miscellaneous income",
    "Re-Bill GST": "miscellaneous income",
    "State Tax": "rooms sales tax",
    "City/Local Tax": "rooms city tax",
    "Occupancy/Tourism": "rooms county occupancy tax",
    "Tax Exempt Rooms": "rooms tax exemptions",
    "Tax Other": "rooms sales tax",
    "Occupancy/Tourism Ta": "rooms county occupancy tax exemptions",
    "Bqt-State Tax": "f and b sales tax",
    "Ctr-State Tax": "f and b sales tax",
    "Telephone Sales Tax": "telephone tax",
    "Valhalla - AX": "amex rooms",
    "Cash": "cash",
    "F&B Cash": "cash",
    "Deposit Rcvd - CA": "cash",
    "Deposit Rcvd - CK": "cash",
    "Deposit Rcvd - DC": "cash",
    "Deposit Rcvd - JC": "cash",
    "Deposit Rcvd - DB": "cash",
    "Deposit Rcvd - SA": "cash",
    "Check": "checks",
    "Mail In Check": "checks",
    "A/R Checks": "eftwire payments",
    "Unicef Donations": "miscellaneous income",
    "Discover Network": "discover rooms",
    "JCB": "misc. credit card payment",
    "Manual Discover Ne": "discover rooms",
    "Manual JCB": "misc. credit card payment",
    "F&B JCB": "misc. credit card payment",
    "Do Not Use": "miscellaneous income",
    "Valhalla - JCB": "misc. credit card payment",
    "paid outs": "paid outs",
    "MasterCard/Euro": "misc. credit card payment",
    "Manual Visa": "visamc rooms",
    "F&B Visa": "visamc f and b",
    "Deposit Rcvd - VI": "Cash",
    "Valhalla - VI": "visamc rooms",
    "Valhalla - DC": "discover rooms",
    "Valhalla - MC": "visamc rooms",
    "F&B MasterCard": "visamc f and b",
    "Vouchers Concierge A": "Miscellaneous receipts",
    "A/R Barter": "Checks",
    "A/R Payment": "checks",
    "A/R Cash": "Cash",
    "Signed Agreement": "Miscellaneous receipts",
    "Room Chrg - Retail": "transient retail",
    "Room Chrg - Non Opaq": "transient retail",
    "Room Chrg - Corp LNR": "transient retail",
    "Room Chrg - Consorti": "transient retail",
    "Rm Chrg - Corp Mkt P": "transient retail",
    "Room Chrg - Qualifie": "transient retail",
    "Room Chrg - GROUP": "transient retail",
    "Early Checkin Fee": "miscellaneous income",
    "Room Charge - Extend": "transient retail",
    "Room Charge Corp Nat": "transient retail",
    "Re:Fuel Food": "restaurant one restaurant other revenue",
    "Re:Tail Store": "restaurant one restaurant other revenue",
    "RE:FUEL Liquor": "restaurant one restaurant other revenue",
    "RE:FUEL Beer": "restaurant one restaurant other revenue",
    "RE:FUEL Wine": "restaurant one restaurant other revenue",
    "WXYZ Food": "restaurant one restaurant other revenue",
    "Food Allowance": "food allowances",
    "WXYZ Liquor": "restaurant one restaurant other revenue",
    "WXYZ Beer": "restaurant one restaurant other revenue",
    "WXYZ Wine": "restaurant one restaurant other revenue",
    "WXYZ State Tax": "rooms sales tax",
    "Beverage Allowance": "beverage allowances",
    "Banquet Food": "banquet food revenue dinner",
    "Bqt-Break": "banquet food revenue breakfast",
    "Bqt-Reception": "banquet food revenue reception",
    "Bqt-Room Rental": "banquet room rental",
    "Bqt-Internet": "internet income",
    "Ctr-Food": "restaurant one restaurant other revenue",
    "Ctr-Break": "banquet food revenue breakfast",
    "Ctr-Reception": "banquet food revenue reception",
    "Ctr-Off Site Breakfa": "banquet food revenue breakfast",
    "Ctr-Off Site Lunch": "banquet food revenue lunch",
    "Ctr-Off Site Dinner": "banquet food revenue dinner",
    "Ctr-Off Site Break": "banquet food revenue breakfast",
    "Ctr-Off Site Recepti": "banquet food revenue reception",
    "Ctr-Off Site Liquor": "banquet beverage revenue liqour",
    "Ctr-Off Site Beer": "banquet beverage revenue beer",
    "Ctr-Off Site Wine": "banquet beverage revenue wine",
    "Ctr-Off Site Other B": "restaurant one restaurant other revenue",
    "Ctr-Room Rental": "banquet room rental",
    "Ctr-Public Rooms #2": "banquet room rental",
    "Ctr-Other Income": "restaurant one restaurant other revenue",
    "Ctr-Internet": "internet income",
    "Ctr-Other Income #1": "restaurant one restaurant other revenue",
    "Telephone": "telephone income local long distance",
    "Laundry/Valet Dry Cl": "guest laundrydry cleaning",
    "Cleaning/Damage Fee": "miscellaneous income",
    "Smoking Fee": "smoking fees",
    "Misc Income #4": "miscellaneous income",
    "Misc Income #5": "miscellaneous income",
    "Signature/Ament Reve": "Miscellaneous receipts",
    "Coin Laundry Machine": "guest laundrydry cleaning",
    "Extra Parking Pass": "parking income",
    "Parking Valet - Day": "parking income",
    "Re:Store Merchandise": "gift shop sales",
    "Paid Out": "paid outs",
    "SPG Instant Award Re": "franchise reimbursement payment",
    "I/C Bliss Spa Servic": "Spa Services",
    "Tax-PST Other": "PST Payable",
    "A/R Misc Income": "miscellaneous income",
    "Tax-GST Other": "GST Payable",
    "Package Re:FUEL": "Miscellaneous Income",
    "Package WXYZ": "Miscellaneous Income",
    "State Recovery Fee": "State Recovery Fee",
    "City Tax": "rooms city tax",
    "TPID": "TPID",
    "TPID Reimbursement": "TPID Reimbursement",
    "RE:FUEL State Tax": "FUEL State Tax",
    "RE:FUEL Gratutity": "f and b tips",
    "WXYZ Gratutity": "f and b tips",
    "Bqt-Sales Tax": "f and b sales tax",
    "Banquet-State Tax": "f and b sales tax",
    "Bqt-Occupancy Tax": "rooms city tax",
    "Bqt-AV/Telecom Tax": "telephone tax",
    "Bqt-Gratuity": "f and b tips",
    "Ctr-Sales Tax": "f and b sales tax",
    "Ctr-A/L Tax Gen#3": "Miscellaneous Non revenue",
    "Ctr-Occupancy Tax": "rooms county occupancy tax",
    "Ctr-AV/Telecom Tax": "telephone tax",
    "Ctr-A/L Tax Gen#1": "telephone tax",
    "Telephone Tax State": "telephone tax",
    "Gratuity/Tips": "Tips",
    "Sales Tax": "rooms sales tax",
    "Cash-Debit Card": "cash",
    "F&B American Expre": "amex f and b",
    "GX Givex Gift Card": "misc. credit card payment",
    "Expedia Wire": "eftwire payments",
    "Wire Transfer": "eftwire payments",
    "SPG Awards": "franchise reimbursement payment",
    "Deposit Rcvd - AC": "Cash",
    "Deposit Rcvd - EFT": "Cash",
    "Deposit Received -": "Cash",
    "Deposit Rcvd - GP": "Cash",
    "Deposit Rcvd - EP": "Cash",
    "Deposit Rcvd - TA": "Cash",
    "Valhalla - DI": "misc. credit card payment",
    "Out of Order Rooms": "Out of Order",
    "Vacant Rooms": "Vacant Rooms",
    "Tele Comm Public Pho": "miscellaneous income",
    "Postage": "miscellaneous income",
    "Wxyz Sales Tax": "sales tax",
    "Internet Svc Custome": "internet income",
    "Package Dining Room": "miscellaneous income",
    "Wireless Phone Fee": "miscellaneous income",
    "Telephone Tax City": "miscellaneous income",
    "Wxyz Gratuity": "Gratuity",
    "Fax/Copies/Scan/Prin": "miscellaneous income",
    "Re:fuel Gratuity": "miscellaneous income",
    "Package Secondary Lo": "miscellaneous income",
    "Re:fuel Sales Tax": "sales tax",
    "Pool Bar Beer": "restaurant one beverage sales beer",
    "Misc Income #1": "miscellaneous income",
    "Telephone Tax PST": "miscellaneous income",
    "Bqt-Other Income-Gen": "miscellaneous income",
    "Package Deli": "miscellaneous income",
    "Room Damage": "DAMAGES ",
    "Pool Bar Liquor": "restaurant one beverage sales LIQUOR",
    "Re:Fuel Retail": "miscellaneous income",
    "Re:fuel Other Bevera": "miscellaneous income",
    "City/Muni 2%": "rooms city tax",
    "Pool Bar Sales Tax": "sales tax",
    "Ctr-Other Income-Gen": "miscellaneous income",
"Direct Bill": "Transfer to Direct Billing from Guest Ledger",
    "Deposit Rcvd - AC": "New Advances Received",
    "Deposit Rcvd - EFT": "New Advances Received",
    "Deposit Received -MC": "New Advances Received",
    "Deposit Rcvd - GP": "New Advances Received",
    "Deposit Rcvd - EP": "New Advances Received",
    "Deposit Rcvd - TA": "New Advances Received",
    "Adv Dep Cancel": "Advances transferred out",
    "Adv Dep DNA": "Advances transferred out"
    }
  },
  {
    "marriotfs": {
    "TRANSIENT ROOM REV": "transient retail",
    "BISTREAUX METAIRIE": "restaurant one restaurant other revenue",
    "SUNDRIES TAX": "grab and go tax",
    "SUNDRY": "miscellaneous income",
    "VALET PARKING": "parking income",
    "PERKS": "miscellaneous income",
    "ROOM TAX": "rooms sales tax",
    "SALES TAX": "rooms sales tax",
    "TAX EXEMPT ROOM REV": "transient retail",
    "VALET PARKING ADJ": "parking income",
    "RACK/BAR": "restaurant one beverage sales other",
    "CORP NEGOTIATED": "transient corporate negotiate",
    "CORP MARKET": "transient corporate marketing programs",
    "OTHER DISC": "transient other discounts",
    "GOVERNMENT": "group government",
    "INTERNET-NOP": "internet income",
    "MERF": "group smerf",
    "REST 1 DISCOUNTS": "cash discounts earned",
    "WIRED FOR BUS-FEE": "eftwire payments",
    "AMEX CLEARING": "amex rooms",
    "VISA/MASTER CARD": "visamc rooms",
    "DISCOVER CLEARING": "discover rooms",
    "GROUP BANQUETS": "group associationconvention",
    "IN ROOM DINING": "room service service charge",
    "PACKAGE ROOM": "transient retail",
    "CATERING ROOM RENTAL": "banquet room rental",
    "BQT/CARTERING TAX": "rooms sales tax",
    "LAUNDRY": "guest laundrydry cleaning",
    "FACILITY FEE": "miscellaneous income",
    "HEALTH CLUB": "miscellaneous income",
    "ROOM REVENUE": "transient retail",
    "EARLY DEPT FEE": "early departure fees",
    "INTERNET": "internet income",
    "DEFAULT ROOM REVENUE": "transient retail",
    "PACKAGE ROOM": "transient retail",
    "STATE TAX": "rooms sales tax",
    "CITY TAX": "rooms city tax",
    "FOOD AND CANDY": "restaurant one restaurant other revenue",
    "SHOP TAX": "miscellaneous tax",
    "STARBUCKS GRAT": "Gratuity",
    "STARBUCKS COFFEE/FD": "restaurant one restaurant other revenue",
    "STARBUCK TAX": "sales tax",
    "RIVER CITY BKFST": "restaurant one restaurant other revenue",
    "RIVER CITY GRAT": "Gratuity",
    "RIVER CITY TAX": "city tax",
    "RIVER CITY LNG FOOD": "restaurant one restaurant other revenue",
    "RIVER CITY LNG BEV": "restaurant one restaurant other revenue",
    "RIVER CITY LNG GRAT": "Gratuity",
    "SILVER BENEFIT ADJ": "miscellaneous income",
    "WIRED FOR BUS FEE": "miscellaneous income",
"DIRECT BILL": "Transfers to Direct Billing from Guest Ledger",
    "GUEST LEDGER": "Guest Ledger",
    "DIRECT BILL": "Transfers to Direct Billing from Guest Ledger"
    }
  },
  {
    "msi": {
  "Room Revenue (Net)": "transient retail",
  "Other Revenue (Net)": "miscellaneous income",
  "Cash": "cash",
  "Vacant Rooms": "Vacant Rooms",
  "Out of Order Rooms": "Out of Order Rooms",
  "Amercian Express": "amex rooms",
  "Check": "Check",
  "Discover Card": "Discover rooms",
  "Mastercard": "visamc rooms",
  "Visa": "visamc rooms",
  "Cancellation Fee": "cancellation fees",
  "County Occupancy Tax": "rooms county occupancy tax",
  "City Occupancy Tax": "rooms city tax",
  "Early Check-in Fee": "miscellaneous income",
  "Food and Beverage": "restaurant two other f and b revenue",
  "Late check-out Fee": "late checkout fees",
  "Meeting Room": "banquet room rental",
  "Miscellaneous": "miscellaneous income",
  "No-Show Charge": "guaranteed no show rooms",
  "Package": "group tourwholesalers",
  "Room Charge": "transient retail",
  "Room Charge Non Ta": "transient retail",
  "Room Charge Tax Inclu": "transient retail",
  "Sales Tax 8.25%": "rooms sales tax",
  "State Occupancy Tax": "rooms county occupancy tax",
  "Snack Shop": "miscellaneous income",
  "State Tax": "State Tax",
  "Vending": "miscellaneous income",
  "Porterage": "amex rooms",
  "Room Revenue": "transient retail",
  "City Tax": "City Tax",
  "COMP": "Complimentray Rooms",
  "BAR": "TRANSIENT- RETAIL",
  "BW": "TRANSIENT- DISCOUNT",
  "EN": "INTERNET OTA- OPAQUE",
  "FX5": "REWARD REDEMPTION",
  "GM": "GOVERNMENT",
  "GROUP": "GROUP - OTHER",
  "NWT": "CORPORATE- LNR",
  "OI": "INTERNET OTA- NON OPAQUE",
  "OTH": "TRANSIENT- RETAIL",
  "PE": "CORPORATE- LNR",
  "Pilgrim": "CORPORATE- LNR",
  "Plantation": "TRANSIENT - PACKAGE",
  "RP": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "TA": "CORPORATE- LNR",
  "TM": "CORPORATE- LNR",
  "TR": "CORPORATE- LNR",
  "WB": "GROUP- SMERFES",
  "Z9": "CORPORATE- LNR",
  "1P": "INTERNET OTA- OPAQUE",
  "3A": "TRANSIENT- DISCOUNT",
  "4190": "No Show",
  "46": "INTERNET OTA- OPAQUE",
  "92": "TRANSIENT- DISCOUNT",
  "9Q": "TRANSIENT- DISCOUNT"
    }
  },
  {
    "newbook": {
      "30' RV Storage": "miscellaneous income",
      "Deluxe Bk-In": "miscellaneous income",
      "Std Pull-thru Cable": "miscellaneous income",
      "Std Pull-Thru": "miscellaneous income",
      "35' RV Storage": "miscellaneous income",
      "25' RV Storage": "miscellaneous income",
      "45' RV Storage ": "miscellaneous income",
      "Laundry Income": "guest laundrydry cleaning",
      "Extras": "miscellaneous income",
      "Cabin": "miscellaneous income",
      "Deluxe RV Cable": "miscellaneous income",
      "Propane Sales": "miscellaneous income",
      " Electric Reimbursement": "miscellaneous income",
      "EFTPOS": "eftwire payments",
      "MasterCard-Gateway Only": "visamc rooms",
      "Visa-Gateway Only": "visamc rooms",
      "Nights Empty": "Vacant Rooms",
      "Growth of Ledger" : "New Book Ledger Summary"
    }
  },
  {
    "onq": {
    "Total Occupied Rooms": "Rooms sold",
    "Corporate Marketing Programs": "transient corporate marketing programs",
    "Corporate Negotiated": "transient corporate negotiate",
    "Other Discounts": "transient other discounts",
    "Trans Suite Medium-Term": "transient retail",
    "Trans Suite Short-Term": "transient retail",
    "Trans Suite Long-Term": "transient retail",
    "Other Beverage Revenue": "restaurant one beverage sales other",
    "Other Revenue": "miscellaneous income",
    "BAR": "transient best available rate",
    "Consortia": "transient consortia",
    "AR Credit Card AMEX": "amex rooms",
    "Sales Tax Payable State": "rooms sales tax",
    "Room Occ Tax Payable - State": "rooms county occupancy tax",
    "HOUSE ACCOUNT BALANCE": "In house",
    "OTHER ITEMS-TRAY": "Closed Folio",
    "AMERICAN EXPRESS CTRL": "amex rooms",
    "AR Credit Card MC Visa": "visamc rooms",
    "MASTERCARD CONTROL": "visamc rooms",
    "VISA CONTROL": "visamc rooms",
    "GROUP MASTER BALANCE": "Group Master",
    "Out of Order Room Nights": "Out of Order room",
    "Vacant Rooms": "Vacant rooms",
    "Day Guest Charges": "transient retail",
    "Guaranteed No Show": "guaranteed no show rooms",
    "Government / Oth. Bus. Disc": "group government",
    "Telephone Local": "telephone income local long distance",
    "Telephone Long Dista": "telephone income local long distance",
    "Long Distance - Inte": "telephone income local long distance",
    "Attrition": "attrition fees",
    "Currency Exchange": "miscellaneous income",
    "Attrition F&B": "attrition fees",
    "Cxl/Attrition": "attrition fees",
    "Gift Certificate Pur": "gift certificate 23140",
    "AR CCard JCB Discover Diners": "misc. credit card payment",
    "Retail Sundries Non-Tax": "miscellaneous income",
    "Breakfast Covers": "restaurant one food sales breakfast",
    "SMERF Room Revenue": "group smerf",
    "Food & Beverage Tax Pay - City": "f and b sales tax",
    "Corp Negotiated Room Revenue": "transient corporate negotiate",
    "Dinner Covers": "restaurant one food sales dinner",
    "Honors Food Contra Revenue": "miscellaneous income",
    "Waiter Fees & Tips Payable": "f and b tips",
    "Trans.Suite/Room Rev.ShortTerm": "transient retail",
    "Local Negotiated Room Revenue": "transient local negotiated",
    "Dinner Food Revenue": "restaurant one food sales dinner",
    "Beer Revenue": "restaurant one beverage sales beer",
    "Discounts Room Rev": "transient discount",
    "Liquor Revenue": "restaurant one beverage sales liquor",
    "Best Available Rate Room Rev": "transient best available rate",
    "Food & Beverage Tax Pay - State": "f and b sales tax",
    "Meeting Room Revenue": "meeting rooms",
    "AR F&B Credit Card AMEX": "amex f and b",
    "Breakfast Food Revenue": "restaurant one food sales breakfast",
    "AR F&B Credit Card MC Visa": "visamc f and b",
    "Corp Mktg Program Room Revenue": "transient corporate marketing programs",
    "Wine Revenue": "restaurant one beverage sales wine",
    "Individual Tour Wholesale Room": "transient wholesale",
    "Service Charge Revenue": "room service service charge",
    "Sales Tax Payable City": "rooms city tax",
    "Service Charge Employee": "room service service charge",
    "Comp Room Nights": "Complimentary rooms",
    "American Express": "amex rooms",
    "Discover": "Discover rooms",
    "ROOMS VACANT": "Vacant rooms",
    "Visa": "visamc rooms",
    "Mastercard": "visamc rooms",
    "STATE SALES TAX": "Sales Tax",
    "CASH PAYMENT": "Cash",
    "CITY OCCUPANCY TAX": "City Tax",
 "TRAY Today's Balance": "Ending Guest Ledger",
"CITY LEDGER Debits": "Transfers to Direct Billing from Guest Ledger",
"CITY LEDGER Credits": "Payments Received Towards City Ledger",
"CITY LEDGER Balance": "Ending City Ledger Net",
"ADVANCE DEPOSITS Debits": "Advances transferred out",
"ADVANCE DEPOSITS Credits": "New Advances Received",
"ADVANCE DEPOSITS Balance": "Ending Advance Deposit Ledger",
 "Deposits - Guest Advance": "Advances transferred out",
    "Advance Deposits Today": "Ending Advance Deposit Ledger",
    "TRAY LEDGER * REQUIRED": "Ending Guest Ledger",
    "AR 90 to 120": "91-120 Days",
    "AR City Ledger": "Transfer to Direct Billing from Guest Ledger",
    "CITY LEDGER * REQUIRED": "Ending City Ledger Net",
    "AR Guest Ledger": "Guest Ledger",
    "AR 1 to 30": "0-30 Days",
    "AR 60 to 90": "61-90 Days",
    "A/R 150 & OVER": "121+ Days",
    "AR 30 to 60": "31-60 Days",
    "AR 120 to 150": "121+ Days"
    }
  },
   {
    "onqexcel": {
    "Total Occupied Rooms": "Rooms sold",
    "Corporate Marketing Programs": "transient corporate marketing programs",
    "Corporate Negotiated": "transient corporate negotiate",
    "Other Discounts": "transient other discounts",
    "Trans Suite Medium-Term": "transient retail",
    "Trans Suite Short-Term": "transient retail",
    "Trans Suite Long-Term": "transient retail",
    "Other Beverage Revenue": "restaurant one beverage sales other",
    "Other Revenue": "miscellaneous income",
    "BAR": "transient best available rate",
    "Consortia": "transient consortia",
    "AR Credit Card AMEX": "amex rooms",
    "Sales Tax Payable State": "rooms sales tax",
    "Room Occ Tax Payable - State": "rooms county occupancy tax",
    "HOUSE ACCOUNT BALANCE": "In house",
    "OTHER ITEMS-TRAY": "Closed Folio",
    "AMERICAN EXPRESS CTRL": "amex rooms",
    "AR Credit Card MC Visa": "visamc rooms",
    "MASTERCARD CONTROL": "visamc rooms",
    "VISA CONTROL": "visamc rooms",
    "GROUP MASTER BALANCE": "Group Master",
    "Out of Order Room Nights": "Out of Order room",
    "Vacant Rooms": "Vacant rooms",
    "Day Guest Charges": "transient retail",
    "Guaranteed No Show": "guaranteed no show rooms",
    "Government / Oth. Bus. Disc": "group government",
    "Telephone Local": "telephone income local long distance",
    "Telephone Long Dista": "telephone income local long distance",
    "Long Distance - Inte": "telephone income local long distance",
    "Attrition": "attrition fees",
    "Currency Exchange": "miscellaneous income",
    "Attrition F&B": "attrition fees",
    "Cxl/Attrition": "attrition fees",
    "Gift Certificate Pur": "gift certificate 23140",
    "AR CCard JCB Discover Diners": "misc. credit card payment",
    "Retail Sundries Non-Tax": "miscellaneous income",
    "Breakfast Covers": "restaurant one food sales breakfast",
    "SMERF Room Revenue": "group smerf",
    "Food & Beverage Tax Pay - City": "f and b sales tax",
    "Corp Negotiated Room Revenue": "transient corporate negotiate",
    "Dinner Covers": "restaurant one food sales dinner",
    "Honors Food Contra Revenue": "miscellaneous income",
    "Waiter Fees & Tips Payable": "f and b tips",
    "Trans.Suite/Room Rev.ShortTerm": "transient retail",
    "Local Negotiated Room Revenue": "transient local negotiated",
    "Dinner Food Revenue": "restaurant one food sales dinner",
    "Beer Revenue": "restaurant one beverage sales beer",
    "Discounts Room Rev": "transient discount",
    "Liquor Revenue": "restaurant one beverage sales liquor",
    "Best Available Rate Room Rev": "transient best available rate",
    "Food & Beverage Tax Pay - State": "f and b sales tax",
    "Meeting Room Revenue": "meeting rooms",
    "AR F&B Credit Card AMEX": "amex f and b",
    "Breakfast Food Revenue": "restaurant one food sales breakfast",
    "AR F&B Credit Card MC Visa": "visamc f and b",
    "Corp Mktg Program Room Revenue": "transient corporate marketing programs",
    "Wine Revenue": "restaurant one beverage sales wine",
    "Individual Tour Wholesale Room": "transient wholesale",
    "Service Charge Revenue": "room service service charge",
    "Sales Tax Payable City": "rooms city tax",
    "Service Charge Employee": "room service service charge",
    "Comp Room Nights": "Complimentary rooms",
    "American Express": "amex rooms",
    "Discover": "Discover rooms",
    "ROOMS VACANT": "Vacant rooms",
    "Visa": "visamc rooms",
    "Mastercard": "visamc rooms",
    "STATE SALES TAX": "Sales Tax",
    "CASH PAYMENT": "Cash",
    "CITY OCCUPANCY TAX": "City Tax",
 "TRAY Today's Balance": "Ending Guest Ledger",
"CITY LEDGER Debits": "Transfers to Direct Billing from Guest Ledger",
"CITY LEDGER Credits": "Payments Received Towards City Ledger",
"CITY LEDGER Balance": "Ending City Ledger Net",
"ADVANCE DEPOSITS Debits": "Advances transferred out",
"ADVANCE DEPOSITS Credits": "New Advances Received",
"ADVANCE DEPOSITS Balance": "Ending Advance Deposit Ledger",
 "Deposits - Guest Advance": "Advances transferred out",
    "Advance Deposits Today": "Ending Advance Deposit Ledger",
    "TRAY LEDGER * REQUIRED": "Ending Guest Ledger",
    "AR 90 to 120": "91-120 Days",
    "AR City Ledger": "Transfer to Direct Billing from Guest Ledger",
    "CITY LEDGER * REQUIRED": "Ending City Ledger Net",
    "AR Guest Ledger": "Guest Ledger",
    "AR 1 to 30": "0-30 Days",
    "AR 60 to 90": "61-90 Days",
    "A/R 150 & OVER": "121+ Days",
    "AR 30 to 60": "31-60 Days",
    "AR 120 to 150": "121+ Days"
    }
  },
  {
    "opera": {
"AR Ledger Payments": "Payments Received Towards City Ledger",
"Deposit Ledger Deposits Transfered at Check-In": "Advances transferred out",
"Deposit Ledger Payments": "New Advances Received",
"AR Ledger Charges and Transfers": "Transfers to Direct Billing from Guest Ledger",
"Direct Billing/City Ledger": "Transfers to Direct Billing from Guest Ledger",
"Guest Ledger Balance Today": "Ending Guest Ledger",
"AR Ledger Balance Today": "Ending City Ledger Net",
  "Rooms Occupied": "Rooms sold",
  "Room Revenue": "transient retail",
  "Candlewood Cupboard": "miscellaneous income",
  "Discount - D": "transient discount",
  "Industry Programs - V": "transient retail",
  "Food And Beverage Revenue": "Food And Beverage Revenue",
  "Other Revenue": "miscellaneous income",
  "Parking": "parking income",
  "Corp-Global - G": "group corporate",
  "Corp-Negotiated Accts - L": "transient corporate negotiate",
  "Corp-Key Accts and BTA - P": "transient corporate negotiate",
  "Long-Term - Y": "transient retail",
  "Package-Leisure - K": "transient retail",
  "Rack - R": "transient retail",
  "City Tax 9%": "rooms city tax",
  "State Tax 6%": "rooms sales tax",
  "Gov/Dipl/Military - M": "Group Government",
  "Wholesale/FIT - W": "transient wholesale",
  "Cash": "cash",
  "Discover": "discover rooms",
  "Pet Fee": "pet fees",
  "House Use - H": "transient retail",
  "Visa": "visamc rooms",
  "American Express": "amex rooms",
  "MasterCard": "visamc rooms",
  "Complimentary Rooms": "complimentary rooms",
  "Available Rooms minus OOO Rooms": "vacant rooms",
  "Out of Order Rooms": "out of order rooms",
  "Out of Service Rooms": "out of order rooms",
  "No Show": "guaranteed no show rooms",
  "Accommodation Upsell": "transient retail",
  "No Show - Adj.": "guaranteed no show rooms",
  "City Tax 9% -Adj": "rooms city tax",
  "State Tax 6% -Adj": "rooms sales tax",
  "JCB": "misc. credit card payment",
  "Late Checkout": "late checkout fees",
  "Mamacitas Brkfst - Food": "banquet food revenue breakfast",
  "Mamacitas Brkfst - Bar": "Restaurant One - Beverage Sales - Other",
  "Mamacitas Lunch - Food": "banquet food revenue lunch",
  "Mamacitas Lunch - Bar": "Restaurant One - Beverage Sales - Other",
  "Mamacitas- Non Alcohol Bev": "Restaurant One - Beverage Sales - Other",
  "Mamacitas Dinner - Food": "banquet food revenue dinner",
  "Mamacitas Dinner - Bar": "Restaurant One - Beverage Sales - Other",
  "Circa 1963 Dinner Food": "banquet food revenue dinner",
  "Grab and Go": "grab and go tax",
  "Mamacitas Alcohol Tax": "f and b sales tax",
  "Mamacitas - Gratuity": "f and b tips",
  "Mamacitas - Food Tax": "f and b sales tax",
  "Circa 1963 Alcohol Tax": "f and b sales tax",
  "Circa Non Alcoholic Beverage": "Restaurant One - Beverage Sales - Other",
  "Circa 1963 Gratuity": "f and b tips",
  "Circa 1963 Food Tax": "f and b sales tax",
  "City Venue Tax 2%": "rooms city tax",
  "County Tax 2.5%": "rooms county occupancy tax",
  "Sales Tax 8.25%": "rooms sales tax",
  "POS - Cash": "cash",
  "POS- American Express": "amex f and b",
  "POS - Visa": "visamc f and b",
  "POS - MasterCard": "visamc f and b",
  "POS - Discover": "discover f and b",
  "POS -Gift Cert": "gift certificate 23140",
  "Unassigned": "transient retail",
  "Complimentary - N": "transient retail",
  "Group - Z": "group smerf",
  "State Tax 6%-Adj": "rooms sales tax",
  "City Tax 7%-Adj": "rooms city tax",
  "City Venue Tax 2%-Adj": "rooms city tax",
  "County Tax 2.5%-Adj": "rooms county occupancy tax",
  "Sales Tax": "Sales Tax",
  "Service charge": "Service charge",
  "NA_RATE_CODE": "OTHER ROOM REVENUE",
  "AE63D": "CORPORATE- LNR",
  "AEPMR": "OTHER ROOM REVENUE",
  "AL0B3": "CORPORATE- LNR",
  "AOAAI": "CORPORATE- OTHER",
  "APARP": "CORPORATE- OTHER",
  "APBCD": "CORPORATE- OTHER",
  "APWTT": "CORPORATE- OTHER",
  "APZGK": "CORPORATE- OTHER",
  "DA13": "TRANSIENT- DISCOUNT",
  "IBGP1": "CORPORATE- OTHER",
  "IDA00": "GROUP - OTHER",
  "IDA0G": "INTERNET OTA- NON OPAQUE",
  "IDA13": "TRANSIENT- DISCOUNT",
  "IDA15": "INTERNET OTA- NON OPAQUE",
  "IDA20": "TRANSIENT- DISCOUNT",
  "IDA25": "TRANSIENT- DISCOUNT",
  "IDAAA": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IDAFS": "TRANSIENT- DISCOUNT",
  "IDAIB": "TRANSIENT- DISCOUNT",
  "IDAMR": "TRANSIENT- DISCOUNT",
  "IDANP": "TRANSIENT- DISCOUNT",
  "IDAP0": "TRANSIENT- DISCOUNT",
  "IDARP": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IDAS1": "TRANSIENT- DISCOUNT",
  "IDAVA": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IDAVC": "INTERNET OTA- NON OPAQUE",
  "IDAWG": "TRANSIENT- DISCOUNT",
  "IDAWV": "INTERNET OTA- NON OPAQUE",
  "IDAX4": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IDBRV": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IDCAP": "CORPORATE- LNR",
  "IDCBW": "TRANSIENT- DISCOUNT",
  "IDDAY": "TRANSIENT- DISCOUNT",
  "IDESS": "TRANSIENT- DISCOUNT",
  "IDGD4": "TRANSIENT- RETAIL",
  "IDH00": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IDH0G": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IDH14": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IDH15": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IDH20": "TRANSIENT- DISCOUNT",
  "IDH25": "INTERNET OTA- NON OPAQUE",
  "IDHCC": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IDHCM": "TRANSIENT- DISCOUNT",
  "IDHCP": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IDHIB": "TRANSIENT- DISCOUNT",
  "IDHNP": "INTERNET OTA- NON OPAQUE",
  "IDHVC": "TRANSIENT- DISCOUNT",
  "IDHWG": "TRANSIENT- DISCOUNT",
  "IDHWV": "TRANSIENT- DISCOUNT",
  "IDIH2": "TRANSIENT- DISCOUNT",
  "IDIN2": "INTERNET OTA- NON OPAQUE",
  "IDINR": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IDL0G": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IDLVC": "CORPORATE- OTHER",
  "IDMAP": "TRANSIENT- DISCOUNT",
  "IDME0": "TRANSIENT- DISCOUNT",
  "IDME1": "TRANSIENT- DISCOUNT",
  "IDME2": "TRANSIENT- DISCOUNT",
  "IDMEF": "TRANSIENT- DISCOUNT",
  "IDMEP": "TRANSIENT- DISCOUNT",
  "IDMES": "GROUP - OTHER",
  "IDOTHENV": "CORPORATE- LNR",
  "IDOTHJAM": "TRANSIENT- DISCOUNT",
  "IDOTHUNH": "TRANSIENT- DISCOUNT",
  "IDPA2": "TRANSIENT- DISCOUNT",
  "IDPB2": "TRANSIENT- DISCOUNT",
  "IDPBI": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IDS00": "TRANSIENT- DISCOUNT",
  "IDS0G": "TRANSIENT- DISCOUNT",
  "IDS14": "TRANSIENT- DISCOUNT",
  "IDS15": "TRANSIENT- DISCOUNT",
  "IDSCC": "TRANSIENT- DISCOUNT",
  "IDSLS": "TRANSIENT- DISCOUNT",
  "IDSP5": "TRANSIENT- DISCOUNT",
  "IDSVC": "TRANSIENT- DISCOUNT",
  "IDSWV": "TRANSIENT- DISCOUNT",
  "IDU00": "CORPORATE- OTHER",
  "IDU0G": "INTERNET OTA- NON OPAQUE",
  "IDU13": "TRANSIENT- DISCOUNT",
  "IDU14": "INTERNET OTA- NON OPAQUE",
  "IDU15": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IDU20": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IDU25": "INTERNET OTA- NON OPAQUE",
  "IDUCC": "TRANSIENT- DISCOUNT",
  "IDUCM": "TRANSIENT- DISCOUNT",
  "IDUIB": "INTERNET OTA- NON OPAQUE",
  "IDUNP": "INTERNET OTA- NON OPAQUE",
  "IDUVC": "INTERNET OTA- NON OPAQUE",
  "IDUWG": "TRANSIENT- DISCOUNT",
  "IDUWV": "TRANSIENT- DISCOUNT",
  "IE3QC": "CORPORATE- OTHER",
  "IEA7U": "CORPORATE- OTHER",
  "IEBS2": "CORPORATE- LNR",
  "IEOH9": "CORPORATE- LNR",
  "IGCL2": "CORPORATE- OTHER",
  "IGCOR": "TRANSIENT- RETAIL",
  "IGM01": "CORPORATE- OTHER",
  "IGM02": "CORPORATE- OTHER",
  "IGM03": "CORPORATE- OTHER",
  "IGM04": "CORPORATE- OTHER",
  "IGM05": "CORPORATE- OTHER",
  "IGM31": "CORPORATE- OTHER",
  "IGM32": "CORPORATE- OTHER",
  "IGM33": "CORPORATE- OTHER",
  "IGN01": "TRANSIENT- DISCOUNT",
  "IGN03": "CORPORATE- OTHER",
  "IGN04": "CORPORATE- OTHER",
  "IGN06": "CORPORATE- OTHER",
  "IGN07": "TRANSIENT- DISCOUNT",
  "IGN1R": "CORPORATE- LNR",
  "IGN2R": "CORPORATE- OTHER",
  "IGN3R": "CORPORATE- OTHER",
  "IGN4R": "CORPORATE- OTHER",
  "IGN5R": "CORPORATE- OTHER",
  "IGN6R": "CORPORATE- OTHER",
  "IGNCS": "CORPORATE- OTHER",
  "IGNP1": "CORPORATE- OTHER",
  "IGNSC": "CORPORATE- OTHER",
  "IGNSD": "CORPORATE- OTHER",
  "IGNSE": "CORPORATE- OTHER",
  "IGNSF": "CORPORATE- OTHER",
  "IGNSL": "CORPORATE- OTHER",
  "IGSNC": "CORPORATE- OTHER",
  "IGTMC": "CORPORATE- OTHER",
  "IKAPA": "TRANSIENT - PACKAGE",
  "IKBPM": "TRANSIENT - PACKAGE",
  "IKDBP": "TRANSIENT - PACKAGE",
  "IKHB4": "TRANSIENT - PACKAGE",
  "IKHD1": "TRANSIENT - PACKAGE",
  "IKHD2": "TRANSIENT - PACKAGE",
  "IKM5K": "TRANSIENT - PACKAGE",
  "IKMA1": "TRANSIENT- DISCOUNT",
  "IKME3": "TRANSIENT - PACKAGE",
  "IKME6": "CORPORATE- OTHER",
  "IKME8": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IKOTH": "TRANSIENT - PACKAGE",
  "IKPCM": "TRANSIENT - PACKAGE",
  "IKPKG": "TRANSIENT - PACKAGE",
  "IKPT5": "TRANSIENT - PACKAGE",
  "IKTH": "CORPORATE- LNR",
  "IL0XQ": "CORPORATE- LNR",
  "IL2WF": "CORPORATE- OTHER",
  "IL4DU": "CORPORATE- LNR",
  "IL5FP": "CORPORATE- OTHER",
  "IL5T0": "CORPORATE- LNR",
  "IL7CZ": "CORPORATE- LNR",
  "IL7NR": "CORPORATE- OTHER",
  "IL8VA": "CORPORATE- LNR",
  "ILCOR": "GROUP - OTHER",
  "ILCORIMS": "CORPORATE- LNR",
  "ILCORMIS": "CORPORATE- LNR",
  "ILCORNAV": "CORPORATE- LNR",
  "ILCOROUE": "CORPORATE- LNR",
  "ILCORUPC": "CORPORATE- LNR",
  "ILEA2": "CORPORATE- LNR",
  "ILETM": "CORPORATE- LNR",
  "ILFE2": "CORPORATE- LNR",
  "ILHJO": "CORPORATE- LNR",
  "ILKO3": "CORPORATE- LNR",
  "ILMTH": "CORPORATE- LNR",
  "ILMZ1": "CORPORATE- LNR",
  "ILOTU": "CORPORATE- LNR",
  "ILRBI": "TRANSIENT- RETAIL",
  "ILREZ": "CORPORATE- LNR",
  "ILSNY": "CORPORATE- LNR",
  "ILSRI": "CORPORATE- LNR",
  "ILSUL": "CORPORATE- OTHER",
  "ILSZB": "CORPORATE- LNR",
  "ILVEW": "CORPORATE- LNR",
  "ILWMZ": "CORPORATE- OTHER",
  "ILWNI": "CORPORATE- LNR",
  "ILXPA": "CORPORATE- OTHER",
  "IMGOV": "GOVERNMENT",
  "IMMLR": "GOVERNMENT",
  "IMSTI": "TRANSIENT- DISCOUNT",
  "INCMP": "COMPLIMENTARY",
  "INIHI": "COMPLIMENTARY",
  "IP2JK": "CORPORATE- OTHER",
  "IPABB": "CORPORATE- OTHER",
  "IPABC": "CORPORATE- OTHER",
  "IPACC": "CORPORATE- OTHER",
  "IPAGT": "CORPORATE- OTHER",
  "IPBCD": "CORPORATE- OTHER",
  "IPBOC": "CORPORATE- OTHER",
  "IPCCR": "CORPORATE- OTHER",
  "IPCTS": "CORPORATE- OTHER",
  "IPCWT": "CORPORATE- OTHER",
  "IPF90": "CORPORATE- OTHER",
  "IPFCI": "CORPORATE- OTHER",
  "IPGOS": "CORPORATE- LNR",
  "IPHON": "CORPORATE- OTHER",
  "IPITL": "CORPORATE- OTHER",
  "IPNCR": "CORPORATE- OTHER",
  "IPORN": "CORPORATE- OTHER",
  "IPPHE": "CORPORATE- OTHER",
  "IPQC4": "CORPORATE- OTHER",
  "IPQCA": "CORPORATE- OTHER",
  "IPSCH": "CORPORATE- OTHER",
  "IPSGV": "CORPORATE- OTHER",
  "IPSTF": "CORPORATE- OTHER",
  "IPTHR": "CORPORATE- OTHER",
  "IPTSA": "CORPORATE- OTHER",
  "IPTT1": "CORPORATE- OTHER",
  "IPUZB": "CORPORATE- OTHER",
  "IPWED": "CORPORATE- OTHER",
  "IPWLA": "CORPORATE- OTHER",
  "ITL5TO": "CORPORATE- LNR",
  "IVACN": "REWARD REDEMPTION",
  "IVAFF1": "REWARD REDEMPTION",
  "IVANI": "REWARD REDEMPTION",
  "IVCF1": "REWARD REDEMPTION",
  "IVCFN": "REWARD REDEMPTION",
  "IVEDI": "TRANSIENT- DISCOUNT",
  "IVFF3": "TRANSIENT- DISCOUNT",
  "IVFFN": "REWARD REDEMPTION",
  "IVHVF": "REWARD REDEMPTION",
  "IVSTF": "REWARD REDEMPTION",
  "IVTCD": "TRANSIENT- DISCOUNT",
  "IWAW5": "CORPORATE- OTHER",
  "IWH25": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IWU25": "TRANSIENT- DISCOUNT",
  "IWY55": "GROUP - TOUR / WHOLESALE",
  "IXC15": "CORPORATE- LNR",
  "IXL1A": "CORPORATE- OTHER",
  "IXNE1": "CORPORATE- OTHER",
  "IXY31": "CORPORATE- LNR",
  "IXY5E": "CORPORATE- OTHER",
  "IYOTH07": "TRANSIENT- RETAIL",
  "IYOTH15": "TRANSIENT- DISCOUNT",
  "IYS00": "TRANSIENT- DISCOUNT",
  "IYS0G": "TRANSIENT- DISCOUNT",
  "IYS14": "INTERNET OTA- NON OPAQUE",
  "IYS15": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IYS25": "TRANSIENT- DISCOUNT",
  "IYSCC": "CORPORATE- LNR",
  "IYSIB": "CORPORATE- OTHER",
  "IYSNP": "TRANSIENT- DISCOUNT",
  "IYSVC": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "IYSWG": "TRANSIENT- DISCOUNT",
  "IYSWV": "TRANSIENT- AAA, AARP, ADV., PUR.",
  "LACI": "CORPORATE- LNR",
  "LAPM": "CORPORATE- LNR",
  "LARCO": "CORPORATE- LNR",
  "LASSLE": "CORPORATE- LNR",
  "LAUB": "CORPORATE- LNR",
  "LAYA": "CORPORATE- LNR",
  "LBROZINI": "CORPORATE- LNR",
  "LCARD": "CORPORATE- LNR",
  "LCES": "CORPORATE- LNR",
  "LCHE": "CORPORATE- LNR",
  "LCIW": "CORPORATE- LNR",
  "LCODAC": "CORPORATE- LNR",
  "LDAF": "CORPORATE- LNR",
  "LDCW": "CORPORATE- LNR",
  "LDNT": "CORPORATE- LNR",
  "LEASTSM": "CORPORATE- LNR",
  "LEUT": "CORPORATE- LNR",
  "LEVERS": "CORPORATE- LNR",
  "LFOARD": "CORPORATE- LNR",
  "LFPH": "CORPORATE- LNR",
  "LGAF": "CORPORATE- LNR",
  "LGCM": "CORPORATE- LNR",
  "LHANFD": "CORPORATE- LNR",
  "LIMAGI": "CORPORATE- LNR",
  "LINTG": "CORPORATE- LNR",
  "LIPS": "CORPORATE- LNR",
  "LJARD": "CORPORATE- LNR",
  "LJBI": "CORPORATE- LNR",
  "LMAD": "CORPORATE- LNR",
  "LMAH": "CORPORATE- LNR",
  "LMAN": "CORPORATE- LNR",
  "LMAR": "CORPORATE- LNR",
  "LMBM": "CORPORATE- LNR",
  "LMCC": "CORPORATE- LNR",
  "LMFW": "CORPORATE- LNR",
  "LMWF": "CORPORATE- LNR",
  "LMWW": "CORPORATE- LNR",
  "LNAM": "CORPORATE- LNR",
  "LNMO": "CORPORATE- LNR",
  "LNPBS": "CORPORATE- LNR",
  "LPALMA": "CORPORATE- LNR",
  "LPEC": "CORPORATE- LNR",
  "LPHE": "CORPORATE- LNR",
  "LPIKE": "CORPORATE- LNR",
  "LPMS": "CORPORATE- LNR",
  "LPRA": "CORPORATE- LNR",
  "LPRATT": "CORPORATE- LNR",
  "LPTC": "CORPORATE- LNR",
  "LRAD": "CORPORATE- LNR",
  "LRAY": "CORPORATE- LNR",
  "LRGM": "CORPORATE- LNR",
  "LRIV": "CORPORATE- LNR",
  "LROYELEC": "CORPORATE- LNR",
  "LRPSNE": "CORPORATE- LNR",
  "LRVW": "CORPORATE- LNR",
  "LSAR": "CORPORATE- LNR",
  "LSCM": "CORPORATE- LNR",
  "LSHE": "CORPORATE- LNR",
  "LSSE": "CORPORATE- LNR",
  "LSTONE": "CORPORATE- OTHER",
  "LTAN": "CORPORATE- LNR",
  "LTDS": "CORPORATE- LNR",
  "LTHCS": "CORPORATE- LNR",
  "LTHWORKS": "CORPORATE- LNR",
  "LTORR": "CORPORATE- LNR",
  "LTOWDUR": "CORPORATE- LNR",
  "LTUF": "CORPORATE- LNR",
  "LTVC": "CORPORATE- LNR",
  "LUNH": "CORPORATE- OTHER",
  "LUNHGY": "CORPORATE- LNR",
  "LUNHHOCK": "CORPORATE- LNR",
  "LUNHLAC": "CORPORATE- LNR",
  "LVALD": "TRANSIENT - PACKAGE",
  "LWILD": "CORPORATE- LNR",
  "NSO": "GROUP - OTHER",
  "TBCU": "CORPORATE- LNR",
  "Z": "GROUP - OTHER",

    }
  },
  {
    "redystay": {
      "STATE TAX": "Sales Tax",
      "SAFE FEE": "Safe Fee",
      "MISC NON-TAX": "miscellaneous income",
      "VENDING REVENUE": "Vending Revenue",
      "CASH": "cash",
      "BUTTON, BRANDON": "guest ledger",
      "CARNEY, AMERA": "guest ledger",
      "NESMITH, APRIL LYNN": "guest ledger",
      "MASTERCARD": "visamc rooms",
      "VISA": "visamc rooms",
      "ROOM CHARGES": "transient retail",
      "HOSP ADJUST": "Hosp adjust",
      "COUNTY TAX": "rooms city tax",
      "Cancelled": "cancellation fees",
      "Total Rooms Occupied" : "Rooms sold",
      "MISC NON-TAX - EARLY CHECK": "miscellaneous income",
      "CHECK": "checks",
      "LOYALTY CERTIFICATE": "miscellaneous income",
      "FREE NIGHT REDEMPTION": "miscellaneous income",
      "AMEX": "amex rooms",
      "Out of Order Rooms": "Out of Order",
      "Comp Rooms": "Complimentary rooms",
      "Total Rooms Left Vacant": "vacant rooms",
    "Advanced Deposit Todays Total": "Ending Advance Deposit Ledger",
    "Advanced Deposit Difference total": "Advances transferred out",
    "Guest Ledger Todays Total": "Ending Guest Ledger",
    "Guest Ledger Difference Total": "Guest Ledger",
    "Company Ledger Todays Total": "Ending Company Ledger Net",
    "Company Ledger Difference Total": "Payments for Company Ledger",
    "Group Ledger Todays Total": "Ending Group Ledger Net",
    "Group Ledger Difference Total": "Group Ledger",
    "City Ledger Todays Total": "Ending City Ledger Net",
    "City Ledger difference Total": "Transfer to Direct Billing from Guest Ledger"   
    }
  },
  {
    "roomkey": {
      "Hotel amenities fee": "miscellaneous income",
      "Hotel Amenities Fees-E-Commerce pre": "miscellaneous income",
      "Parking Charge": "parking income",
      "Pet Fee ": "pet fees",
      "miscellaneous income": "miscellaneous income",
      "American Express": "amex rooms",
      "Debit ": "misc. credit card payment",
      "Mastercard": "visamc rooms",
      "VISA": "visamc rooms",
      "E-Commerce Room Charge Prepaid": "transient retail",
      "Room Charge": "transient retail",
      "GST": "rooms sales tax",
      "Hotel Tax": "rooms sales tax",
      "HST": "rooms sales tax",
      "MRTD": "rooms sales tax",
      "PST": "rooms sales tax",
      "PST Room 8%": "rooms sales tax",
      "Room Tax": "rooms sales tax",
      "Guest Recovery": "miscellaneous income",
      "Room Charge GST Only ": "transient retail",
      "Amenity Fee ": "miscellaneous income",
      "Breakfast Adult ": "restaurant one food sales breakfast",
      "Sea 2 Sky Gondola Commision": "commission income",
      "Housekeeping Gratuities": "f and b tips paid out",
      "Meeting Room Rental ": "banquet av rental revenue",
      "Owner Cleaning Charge": "room service service charge",
      "Pet Weekly Fee Aug 19": "pet fees",
      "Smoking Fee ": "smoking fees",
      "Sundry Sales": "miscellaneous income",
      "Cheque ": "checks",
      "Crew Room Charge ": "transient retail",
      "Long term stay ": "transient retail",
      "Best Available Room Charge ": "transient best available rate",
      "Discount General Room Charge": "transient discount",
      "Group Corporate Room Charge ": "group corporate",
      "Group SMERFE Room Charge ": "group smerf",
      "Corporate Locally Negotiated Room ": "transient corporate negotiate",
      "Package Room Charge ": "transient wholesale",
      "Provincial Government Room Charge ": "group government",
      "guest laundrydry cleaning": "guest laundrydry cleaning",
      "pet fees": "pet fees",
      "Miscellaneous (Retail) ": "miscellaneous income",
      "parking income": "parking income",
      "transient retail": "transient retail",
      "Room Charge - GST and DMF only": "transient retail",
      "Out of Order": "Out of Order",
      "Complimentary": "Complimentary",
      "M & M's Candy" : "Meeting Room Food Revenue",
      "Skittles - Candy" : "Meeting Room Food Revenue",
      "Discover" : "Discover Rooms",
      "Municipal Accommodation Tax" : "Taxes",
      "Crown Royal Whiskey" : "food & beverage",
      "Tito's Vodka" : "food & beverage",
      "Cash" : "Cash"
    } 
  },
  {
    "synxis": {
      "RM - Total": "transient retail",
      "1000 - Total": "rooms city tax",
      "AX - Total": "amex rooms",
      "CA - Total": "cash",
      "NS - Total": "guaranteed no show rooms",
      "DS - Total": "discover rooms",
      "CK - Total": "checks",
      "MC - Total": "visamc rooms",
      "VI - Total": "visamc rooms",
      "OOO Rooms": "out of order rooms",
      "Rooms Left Vacant": "vacant rooms",
      "1001 - Total": "rooms sales tax",
      "OOO Rooms": "out of order rooms",
      "Rooms Left Vacant": "vacant rooms",
      "MARTWA - Total" : "Mini Mart Water",
      "MARTFD - Total" : "Mini Mart Food",
      "1001 - Total": "rooms sales tax",
"Guest Ledger Today Total": "Ending Guest Ledger",
"Guest Ledger Difference": "Guest Ledger",
"Group Ledger Today Total": "Ending Group Ledger Net",
"Group Ledger Difference": "Group Ledger",
"AR Ledger Today Total": "Ending City Ledger Net",
"AR Ledger Difference": "Transfer to Direct Billing from Guest Ledger",
"House Ledger Today Total": "Ending House Ledger Net",
"House Ledger Difference": "Payments for House Ledger"
    }
  },
  {
    "visualmatrix": {
      "Corporate Negotiated Rate": "transient corporate negotiate",
      "Discount Rate": "transient discount",
      "BW CENTRAL RESERVATIONS": "transient retail",
      "Government Rate": "group government",
      "COMP MEETING ROOM": "banquet room rental",
      "CRIB": "miscellaneous income",
      "MISC. ADJUSTMENT": "miscellaneous income",
      "IN-ROOM MOVIES CHRGS": "movie rental",
      "MISC. CHARGE": "miscellaneous income",
      "MEETING ROOM": "banquet room rental",
      "RESTAURANT": "restaurant one beverage sales other",
      "SAFE": "miscellaneous income",
      "WALK-IN GUEST": "Walk in Guest",
      "PET FEE": "pet fees",
      "LONG DIST PHONE CHRGS": "telephone income local long distance",
      "REFUND AMEX": "amex rooms",
      "REFUND DINERS": "misc. credit card payment",
      "CITY TAX": "rooms city tax",
      "COUNTY TAX": "rooms county occupancy tax",
      "STATE TAX": "rooms sales tax",
      "PAYMENT CASH": "cash",
      "REFUND CASH": "cash",
      "PAYMENT CHECK": "checks",
      "REFUND CHECK": "checks",
      "REFUND DISCOVER": "discover rooms",
      "PAYMENT AMEX": "amex rooms",
      "PAYMENT DISCOVER": "discover rooms",
      "PAYMENT DINERS": "misc. credit card payment",
      "Out of serivce": "Out of order",
      "Comps": "Complimentary rooms",
      "Occupied" : "Rooms sold",
      "REFUND VISA/MC": "visamc rooms",
      "STATE TAX ADJ": "rooms sales tax",
      "CITY TAX ADJ": "rooms city tax",
    "Guest Ledger Closing": "Ending Guest Ledger",
    "City Ledger Debits": "Transfer to Direct Billing from Guest Ledger",
    "City Ledger Credits": "Payments Received Towards City Ledger",
    "City Ledger Closing": "Ending City Ledger Net",
    "Advance Deposits Debits": "Advances transferred out",
    "Advance Deposits Credits": "New Advances Received",
    "Advance Deposits Closing": "Ending Advance Deposit Ledger"
    }
  },
  {
    "webrezpro": {
    "49010 Cancellation Fees E": "cancellation fees",
    "Visa Merchant": "visamc rooms",
    "Mastercard Merchant": "visamc rooms",
    "22020 HLA Collected E": "rooms sales tax",
    "22040 CA Tourism Assessment Fee Collected E": "rooms county occupancy tax",
    "42010 Telephone Revenue E": "telephone income local long distance",
    "42020 Snack Shack Income E": "miscellaneous income",
    "42030 Pool Party revenue E": "miscellaneous income",
    "42040 Meeting Room revenue E": "banquet room rental",
    "42050 Smoking fee revenue E": "smoking fees",
    "42060 Pet fee revenue E": "pet fees",
    "42080 LunchBox E": "miscellaneous income",
    "42090 Bar E": "restaurant one beverage sales other",
    "11010 Cash/cheque E": "cash",
    "11020 Visa Merchant E": "visamc rooms",
    "11030 Mastercard Merchant E": "visamc rooms",
    "11040 AMEX Merchant E": "amex rooms",
    "11050 Funds Trransferred E": "eftwire payments",
    "22020 VAT Collected E": "rooms sales tax",
    "22021 OVC Gratuities Collected E": "f and b tips",
    "22021 TOS Gratuities Collected E": "f and b tips",
    "20105 OVC Room Revenue E": "transient retail",
    "20125 OVC Misc Income E": "miscellaneous income",
    "30105 TOS Room Revenue E": "transient retail",
    "30110 TOS Food Revenue E": "restaurant two other f and b revenue",
    "TOS Food Revenue": "restaurant two other f and b revenue",
    "OVC Food Revenue": "restaurant two other f and b revenue",
    "TOS Room Revenue": "transient retail",
    "OVC Room Revenue": "transient retail",
    "OVC Misc Income": "miscellaneous income",
    "OVC Gratuities 15%": "f and b tips",
    "VAT 10%": "rooms sales tax",
    "TOS Gratuities 15%": "f and b tips",
    "PREARRIVAL_CHARGES_ADJ": "miscellaneous income",
    "OUT OF ORDER": "Out of Order",
    "COMP ROOMS": "Complimentary Rooms",
    "11010 Cash/Check E": "cash",
    "11020 Visa Merchant E": "visamc rooms",
    "11030 Mastercard Merchant E": "visamc rooms",
    "11040 AMEX Merchant E": "amex rooms",
    "11050 Discover Merchant": "discover rooms",
    "11060 Funds Transfer E": "eftwire payments",
    "22040 TOT Collected E": "rooms county occupancy tax",
    "41010 Room Revenue": "transient retail",
    "42070 Lobby Item revenue E0": "Lounge - Other F & B Revenue",
    "Pool Party revenue": "miscellaneous income",
    "Room Revenue": "transient retail",
    "Pet fee revenue": "pet fees",
    "Cash/Check": "Cash",
    "HLA": "rooms sales tax",
    "CA Tourism Assessment Fee": "rooms county occupancy tax",
    "TOT": "rooms county occupancy tax",
    "22030 TOT Collected E": "rooms county occupancy tax",
    "42070 Lobby Item revenue E": "Lounge - Other F & B Revenue",
"XFER TO GUEST LEDGER": "Advances transferred out",
    "XFER FROM GUEST LEDGER": "Transfer to Direct Billing from Guest Ledger",
    }
  }
]

json_string = {
  "room rent": "transient retail"
}

@app.get("/", include_in_schema=False)
async def root():
    return RedirectResponse(url="/docs")

class DataFrameObject(BaseModel):
    dataframe: list[dict[str, str]]
    key: str
    pms: str
    
@app.post("/lineitem", response_class=JSONResponse)   
async def get_openai_response(input_text:dict):
    # print("Incoming Input text from Extraction API ------", input_text)
    data = json.loads(input_text['DataFrame_Object'])
    pms = data['pms']
    lineitems_list = []
    for item in data['dataframe']:
        item =item['lineitem_desc']
        lineitems_list.append(item)
    # print(lineitems_list)
    
    lineitems = ', '.join(lineitems_list)
    print("----------------------------------------LINEITEMS given to Prompt----------------------------------------")
    print(lineitems)
    print("----------------------------------------LINEITEMS COUNT----------------------------------------")
    print(len(lineitems_list))
    # Check if pms is present in all_pms_data and retrieve pms_dict
    pms_dict = None
    for pms_data in all_pms_data:
        if pms in pms_data:
            pms_dict = pms_data[pms]
            break
    if pms_dict is None:
        return JSONResponse(content={"error": f"{pms} is not found in the list"}, status_code=400)
    # Open AI prompt
    prompt = f"You will be given hotel PMS reports consisting line items of daily sales. Your task is to map every line items from the line item list to the particular label based on the provided dictionary. If the line items are not present in the dictionary then you will understand dictionary mapping pattern and map the new line items to the most probable label(value) in the dictionary. Make sure that the number of input line items and output json items are equal. Your response will be in JSON format only with no extra information{json_string}. Here is the dictionary:{pms_dict}. Here are your line items :"

    prompt2_gpt = prompt + lineitems
    print("----------------------------------------COMPLETE PROMPT----------------------------------------")
    # print(prompt2_gpt)

    # Send request to OpenAI API
    response = requests.post(
        url="https://api.openai.com/v1/chat/completions",
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
        },
        json={
            "model": "gpt-3.5-turbo",  # we can change models here
            "messages": [
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": prompt2_gpt},
            ],
            "response_format": {"type": "json_object"},
            "temperature": 0.2,
        },
    )

    # Handle response
    if response is not None:
        print(response.text)  
    try:
        resjson = json.loads(response.text)

        if "error" in resjson:
            print(resjson)
            # Handle error if needed

        content = resjson["choices"][0]["message"]["content"]
        print("----------------------------------------FINAL RESPONSE STARTS----------------------------------------")
        print(content, type(content))
        print("----------------------------------------FINAL RESPONSE ENDS----------------------------------------")
        return content
    except Exception as ex:
        print(f"Exception during extraction {ex}")
        return JSONResponse(content={"error": str(ex)}, status_code=500)


if __name__ == "__main__":
    uvicorn.run("api_final:app", host="localhost", port=8000, reload=True)
